export const cities = () =>{
    return [
        "SANIBEL",
        "PUNTA GORDA",
        "NORTH FORT MYERS",
        "ALVA",
        "Babcock Ranch",
        "EVERGLADES CITY",
        "LABELLE",
        "PORT CHARLOTTE",
        "FORT DENAUD",
        "ST. JAMES CITY",
        "MIROMAR LAKES",
        "PLACIDA",
        "BOKEELIA",
        "VENUS",
        "DE LAND",
        "DAVENPORT",
        "MOORE HAVEN",
        "MIAMI",
        "CLEWISTON",
        "TITUSVILLE",
        "CAPTIVA",
        "CITRUS SPRINGS",
        "NORTH PORT",
        "Upper Captiva",
        "ROTONDA WEST",
        "FORT MYERS BEACH",
        "WEBSTER",
        "ENGLEWOOD",
        "OTHER",
        "INDIAN LAKE ESTATES",
        "FOUNTAIN",
        "OCALA",
        "MONTURA RANCHES",
        "ARCADIA",
        "USEPPA ISLAND",
        "SUMMERFIELD",
        "NEW PORT RICHEY",
        "DORAL",
        "OUT OF AREA",
        "AVON PARK",
        "LAKE PLACID",
        "SEBRING",
        "ALFORD",
        "MATLACHA",
        "IMMOKALEE",
        "PANAMA CITY",
        "AVE MARIA",
        "OCKLAWAHA",
        "PENSACOLA",
        "INTERLACHEN",
        "FLORAHOME",
        "CRESTVIEW",
        "SILVER SPRINGS",
        "PALATKA",
        "SATSUMA",
        "CRYSTAL RIVER",
        "HUDSON",
        "DAYTONA BEACH",
        "MARIANNA",
        "TALLAHASSEE",
        "LIVE OAK",
        "LAKE CITY",
        "QUINCY",
        "SAN MATEO",
        "MILTON",
        "LAKE WALES",
        "OKEECHOBEE",
        "APOPKA",
        "HAWTHORNE",
        "DUNNELLON",
        "FELDA",
        "PALM COAST",
        "KEY LARGO",
        "GOODLAND",
        "MATLACHA ISLES",
        "SARASOTA",
        "BRADENTON",
        "KEY WEST",
        "PALM BAY",
        "BELLEVIEW",
        "LAKE SUZY",
        "Cayo Costa",
        "WILLISTON",
        "GULF BREEZE",
        "POLK CITY",
        "GRANT",
        "KISSIMMEE",
        "MELBOURNE",
        "DUNEDIN",
        "CHATTAHOOCHEE",
        "HAVANA",
        "HERNANDO",
        "OLD TOWN",
        "BEVERLY HILLS",
        "JACKSONVILLE",
        "PORT ST. LUCIE",
        "LAKELAND",
        "GREEN COVE SPRINGS",
        "LECANTO",
        "WELAKA",
        "WEWAHITCHKA",
        "LAWTEY",
        "HOMOSASSA",
        "BASCOM",
        "CITRA",
        "TRENTON",
        "MYAKKA CITY",
        "OSPREY"
    ].sort()
}