import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
import * as cities from './cities'
export const fetchCity = createAsyncThunk('res/fetchCity', (id) => {
    console.log("reached", id)
    return [];
})

const addCityOptions = (state, action) =>{
    var cityOptions = action.payload;
  return {
      ...state,
      cityOptions: cityOptions
    }
}

export const ResSearchFields = createSlice({
    name: 'res',
    initialState: {
        previousPages: [
            {page:0, start:0, index:0}
        ],
        page: 0,
        limit: 10,
        order: 'desc',
        sortBy: 'ModificationTimestamp',
        keyword: '',
        PropertyType: ['Residential', 'Residential Income', 'Commercial Sale'],
        city: '',
        cityOptions: [
            "NAPLES",
            "BONITA SPRINGS",
            "ESTERO",
            "MARCO ISLAND",
            "CAPE CORAL",
            "LEHIGH ACRES",
            "FORT MYERS",
            ...cities.cities()
        ],
        community: '',
        communityOptions: [
            "VANDERBILT LAKES",
            "BERKSHIRE LAKES",
            "THE DUNES OF NAPLES",
            "SANDALWOOD VILLAGE",
            "PELICAN BAY",
            "AQUALANE SHORES",
            "NAPLES PARK",
            "CAPE CORAL",
            "OLDE NAPLES",
            "PALM RIVER",
            "LELY RESORT",
            "LITTLE HICKORY",
            "NOT APPLICABLE",
            "TREVISO BAY",
            "MIRASOL AT COCONUT POINT",
            "FIDDLER'S CREEK",
            "EDGEWATERS GARDENS",
            "RIVER TOWERS",
            "BRIARWOOD",
            "The Place At Corkscrew",
            "DAVIS LAKE CONDO",
            "THE PINES",
            "SATURNIA LAKES",
            "MEDITERRA",
            "SORRENTO VILLAS",
            "OLDE CYPRESS",
            "PELICAN MARSH",
            "HUNTINGTON LAKES",
            "ROYAL ARMS EXTENSION",
            "NAVARRA PARK",
            "VANDERBILT SHORES",
            "SHADOW WOOD AT THE BROOKS",
            "HERITAGE POINTE",
            "STERLING OAKS",
            "STONECREEK",
            "KALEA BAY",
            "BABCOCK",
            "IBIS WOODS",
            "BURNT STORE MARINA",
            "MATLACHA",
            "CENTRAL PARK SOUTH CONDOS",
            "HAMMOCK BAY GOLF AND COUNTRY CLUB",
            "CARLTON LAKES",
            "VANDERBILT BEACH",
            "COQUINA SANDS",
            "BONITA NATIONAL GOLF AND COUNTRY CLUB",
            "SEYCHELLES",
            "CALOOSA ISLES II CONDO",
            "LEHIGH ACRES",
            "PROVINCETOWN",
            "NAPLES HIDEAWAY CLUB",
            "COUNTRY CREEK",
            "PRIVATEER OF FT MYERS BEACH",
            "MARCO SHORES",
            "OYSTER BAY",
            "HERITAGE LANDING GOLF AND COUNTRY CLUB",
            "EAGLE CREEK",
            "HACIENDA LAKES",
            "RIVERBEND MOTORCOACH RESORT",
            "MARCO ISLAND",
            "NAPLES CAY",
            "DONAX VILLAGE CONDO",
            "WIGGINS BAY",
            "EVERGLADES TOWN",
            "GOLDEN GATE ESTATES",
            "KEY MARCO",
            "WEST BAY CLUB",
            "REFLECTION LAKES",
            "ROYAL PALM GOLF ESTATES",
            "SEASONS AT BONITA",
            "SORRENTO",
            "BONITA FARMS",
            "SOUTH GULF COVE",
            "PORT LABELLE",
            "COPPER OAKS",
            "WINDSTAR",
            "EMERALD BAY",
            "LELY",
            "PARK SHORE",
            "WOODSTONE",
            "TUSCANY GARDENS",
            "VILLAGE WALK OF BONITA SPRINGS",
            "PELICAN LANDING",
            "MOORINGS",
            "NAPLES SANDPIPER BAY CLUB",
            "PAVILION CLUB",
            "TALIS PARK",
            "GLEN EAGLE",
            "SAPPHIRE LAKES",
            "ORCHARDS",
            "VANDERBILT VILLAS",
            "HERITAGE BAY",
            "BAY FOREST",
            "FOREST LAKES",
            "BRIDGEWATER BAY",
            "BONITA BAY",
            "COPPERLEAF AT THE BROOKS",
            "BEACH WALK CONDO",
            "CAY LAGOON",
            "VINEYARDS",
            "LELY COUNTRY CLUB",
            "FOREST GLEN",
            "CYPRESS GLEN",
            "FURSE LAKES",
            "STONEBRIDGE",
            "ROYAL HARBOR",
            "COLONIAL COUNTRY CLUB",
            "VASARI",
            "WORTHINGTON",
            "BERMUDA CLUB CONDO",
            "HAMILTON PLACE",
            "LAMORADA",
            "FORT MYERS BEACH",
            "ESPLANADE",
            "COTTAGE POINT UNREC",
            "MARQUESA ISLES OF NAPLES",
            "HIDDEN LAKES AT WOODS EDGE",
            "CAPE HARBOUR",
            "LAKESIDE",
            "PASEO",
            "TANGLEWOOD",
            "LONGSHORE LAKE",
            "ANDALUCIA",
            "WORLD TENNIS CENTER",
            "CYPRESS WOODS GOLF AND COUNTRY CLUB",
            "SHERWOOD",
            "WIGGINS LAKES AND PRESERVES",
            "HERONS GLEN",
            "COCONUT POINT",
            "FOUNTAIN LAKES",
            "FOREST VILLAGE",
            "LITTLE HICKORY SHORES",
            "ISLAND COVE OF CAPE CORAL",
            "PARKER LAKES",
            "FORT DENAUD ACRES",
            "ISLES OF COLLIER PRESERVE",
            "PELICAN SOUND",
            "HALLENDALE",
            "BONITA SPRINGS",
            "VANDERBILT COUNTRY CLUB",
            "BELLA TERRA",
            "PINE RIDGE",
            "BONITA SHORES",
            "BUTTONWOOD KEY",
            "ACREAGE HEADER",
            "KEEWAYDIN ISLAND",
            "RIVERWOOD",
            "INDIGO LAKES",
            "COUNTRY CLUB ESTATES",
            "SPANISH WELLS",
            "BAY COLONY",
            "SAIL HARBOUR",
            "STELLA MARIS",
            "ARTESIA",
            "MIROMAR LAKES BEACH AND GOLF CLUB",
            "LELY GOLF ESTATES",
            "BONITA BEACH CLUB",
            "GULF HARBOUR YACHT AND COUNTRY CLUB",
            "RESERVE AT NAPLES",
            "NORTH STAR YACHT CLUB",
            "SANIBEL VIEW CONDO",
            "PUNTA GORDA",
            "PIRATES COVE",
            "MOORE HAVEN",
            "SAN CARLOS PARK",
            "SOUTH SEAS CLUB CONDO",
            "SAVONA",
            "NAPLES SQUARE",
            "TROPICAL GULF ACRES",
            "PALM BAY ESTATES",
            "MILLERS PARK",
            "LABELLE ESTATES",
            "PORT OF THE ISLANDS",
            "BURNT STORE LAKES",
            "CORDERA",
            "MONTURA",
            "SUNCOAST ESTATE",
            "RUSSELL PARK",
            "CHARLOTTE SHORES",
            "SOUTH SEAS ISLAND RESORT",
            "MARGARET ACRES",
            "COUNTRYSIDE",
            "HUNTERS RIDGE",
            "BEACHWALK",
            "CITRUS SPRINGS",
            "NORTH PORT",
            "BURNT STORE MEADOWS",
            "KREAMERS AVOCADO SUBD",
            "PORT CHARLOTTE",
            "GREENBRIAR",
            "LAKE MUREX",
            "NORTH FORT MYERS",
            "TIMBER TRAILS",
            "GULF COVE",
            "PINE ISLAND RIDGE",
            "BUCKINGHAM",
            "ROTONDA SANDS",
            "GRACIOUS HOMES SUBD",
            "NORTH CAPTIVA DUNES",
            "RIVERCREEK",
            "TOWN AND RIVER",
            "METES AND BOUNDS",
            "BAYVIEW ACRES",
            "REGENT PARK",
            "NAPLES RESERVE",
            "FORT MYERS",
            "THE SANCTUARY",
            "NORTH BELLE MEADE",
            "GLADES COUNTY",
            "STONEYBROOK",
            "LEILANI",
            "PLANTATION ISLAND",
            "CROWN POINTE",
            "BAREFOOT BEACH",
            "GULF ACRES",
            "BEARS PAW",
            "CONCORDIA",
            "BUCKINGHAM PARK",
            "FOXFIRE",
            "DELASOL",
            "VILLAS ENCANTADA",
            "THE STRAND",
            "KNIGHTS BOKEELIA ISLE",
            "EL DORADO ACRES",
            "HERITAGE GREENS",
            "LEHIGH ESTATES",
            "LABELLE",
            "SHERRILL POINT",
            "IMPERIAL GOLF ESTATES",
            "THE ENCLAVE AT NAPLES",
            "HIGHLAND ESTATES UNRECORDED SUBDIVISION",
            "CALOOSA HAMMOCK",
            "ACREAGE",
            "LAKEVILLE",
            "NAPLES CLUB ESTATES",
            "BAYFRONT",
            "BONITA BEACH",
            "WHISKEY CREEK",
            "MOODY RIVER ESTATES",
            "PELICAN PRESERVE",
            "NEWPORT MANORS CONDO",
            "SPRING CREEK",
            "PORT AU PRINCE",
            "SPRING WOODS M/H SUBD",
            "SHADOWLAWN AT NAPLES",
            "TWIN LAKE ESTATES",
            "ALVA",
            "WEST LEHIGH",
            "MIRROR LAKES",
            "LOGAN WOODS",
            "MUSE",
            "PINELAND",
            "WEST WIND ESTATES",
            "CAYO COSTA",
            "CORAL RIDGE ESTATES",
            "CHOKOLOSKEE",
            "WHEELERS SUBD",
            "ROTONDA WEST",
            "GRAMAC",
            "SEASPRAY SUBDIVISION",
            "ROSEMARY PARK",
            "SOUTH PUNTA GORDA HEIGHTS",
            "ROTONDA HEIGHTS",
            "SUNNY PALM ESTATES",
            "OKEECHOBEE",
            "OAKLAND PARK TRAILER SITES",
            "BONITA LAKES",
            "BOCILLA ISLAND CLUB CONDO",
            "COUNTRY CLUB MANOR",
            "COACH HOUSE",
            "RIVERSIDE CLUB",
            "BERMUDA POINTE",
            "FOUR SEASONS",
            "SEASCAPE",
            "THE COLONY AT PELICAN LANDING",
            "THE PLANTATION",
            "CALUSA BAY NORTH",
            "MEADOWLARK ESTATES",
            "PELICAN RIDGE",
            "SUNCOAST ESTATES UNREC",
            "SHELL HARBOR",
            "PALMETTO PINES COUNTRY CLUB",
            "INDIAN HILLS",
            "JOSE'S HIDEAWAY",
            "CHARLOTTE HARBOUR",
            "LEHIGH PROPERTIES",
            "MARION OAKS",
            "PUNTA GORDA ISLES",
            "HARBOR HEIGHTS",
            "CHARLOTTE RANCHETTES",
            "RIVERBEND",
            "BURNT STORE VILLAGE",
            "SUNDIET VILLAGE",
            "COCONUT GROVE UNREC",
            "ROTONDA LAKES",
            "QUAIL WEST",
            "WILDCAT FARMS",
            "CALOOSA ESTATES",
            "PORT ROYAL",
            "GULF HAVEN",
            "CAPE ROMANO",
            "ALTA MAR",
            "CENTRAL HENDRY COUNTY",
            "BEACHVIEW COUNTRY CLUB ESTATES",
            "PIONEER PLANTATION",
            "CASA BONITA",
            "PINE ISLAND",
            "GERBER GROVES",
            "DEVONWOOD",
            "RENAISSANCE",
            "PIRATE HARBOR",
            "OLD FORT DENAUD",
            "COPELAND VILLAGE",
            "PINE ISLAND CENTER",
            "MOSS PARK",
            "JOYCE PARK",
            "FORT MYERS GULF ACRES",
            "CASTAWAY KEY UNRECORDED SUBDIVISION",
            "CLEWISTON",
            "ROTONDA VILLAS",
            "PAGE PARK",
            "LEISURE ACRES",
            "FRANK C ADAMS SUBDIVISION UNRECORDED SUBDIVISION",
            "SOUTHWOOD",
            "900 BUILDING",
            "CAPTAINS COVE",
            "PINE ISLAND SHORES UNIT 5",
            "USEPPA ISLAND",
            "ROYAL PALM PARK",
            "HICKEY CREEKSIDE",
            "CALOOSA PRESERVE",
            "SKY MANOR ESTATES",
            "EAGLE ACRES",
            "GALT ISLAND SHORES",
            "SOUTHERN HEIGHTS",
            "HARLEM HEIGHTS",
            "OAK RIDGE",
            "FORT MYERS SHORES",
            "UPPER CAPTIVA SHORES",
            "YACHT CLUB COLONY",
            "EMERALD LAKES",
            "OASIS",
            "RIVERSTONE",
            "NAPLES BAY RESORT",
            "ELEVEN ELEVEN CENTRAL",
            "GATOR CIRCLE",
            "MARCO BEACH",
            "SAFETY HARBOR CLUB",
            "SAN CARLOS PARK GOLF COURSE ADDITION",
            "RIVER FOREST",
            "PALMONA PARK",
            "COMPASS LANDING",
            "ARBORWOOD PRESERVE",
            "HIGHLAND WOODS",
            "CORAL CAY CONDO",
            "WINTERPARK",
            "TARPON POINT MARINA",
            "THE GRANDE PRESERVE",
            "NORTHSHORE LAKE VILLAS",
            "BRIDGEWATER",
            "ISLAND BREEZE",
            "HERITAGE PALMS GOLF AND COUNTRY CLUB",
            "MARSH LANDING",
            "MARBELLA ISLES",
            "STRATFORD PLACE",
            "ST CROIX",
            "WOODS EDGE",
            "GOLDEN SHORES",
            "MASTIQUE",
            "GOLDEN GATE CITY",
            "GLADES",
            "WING SOUTH AIRPARK",
            "RIVIERA COLONY",
            "COCONUT SHORES",
            "FALLING WATERS",
            "BURNT STORE WEST",
            "IMMOKALEE ANCHORAGE",
            "ADMIRALS WALK",
            "LINDSFORD",
            "ONYX TOWNHOME VILLAS",
            "ADMIRAL LEHIGH ESTATES",
            "WHIPPOORWILL",
            "SPRING RUN AT THE BROOKS",
            "IBIS COVE",
            "HAWKSRIDGE",
            "IBIS CLUB INTERNATIONAL",
            "FOREST PARK",
            "PROVINCE PARK",
            "VILLAGE GREEN",
            "DIXON PARK",
            "HOMESTEAD PARK",
            "PARQUE DE LEON",
            "PALMETTO POINT",
            "ISLES OF CAPRI",
            "WEBER WOODS",
            "NAPLES BETTER HOMES",
            "MANGROVE BAY",
            "ANTILLES",
            "MARINA BAY",
            "PARKWOODS TOWNHOUSE COMMUNITY",
            "MCGREGOR ISLES",
            "WHEELERS H L SUBD",
            "LELY PINES",
            "TEN MILE ANCHORAGE",
            "BURTWOOD",
            "DANFORTH LAKES",
            "BRIARCLIFF",
            "THE NATIONAL GOLF & COUNTRY CLUB AT AVE MARIA",
            "SANDOVAL",
            "VALENCIA BONITA",
            "PARADISE SHORES",
            "ST JUDE HARBORS",
            "KINGS LAKE",
            "KREAMERS SUBD",
            "BIG CYPRESS",
            "TERRACES AT RIVERWALK",
            "BUTTONWOOD HARBOR",
            "EAST STADLER FARMS",
            "GULF WINDS EAST",
            "HENDERSON CREEK PARK",
            "BAY POINTE YACHT & RACQUET CLUB",
            "CAMDEN COVE",
            "RIVER TOWERS CONDO",
            "LOVERS KEY BEACH CLUB",
            "ORANGE BLOSSOM RANCH",
            "COLLEGE POINTE",
            "VILLAGE WALK",
            "ISLAND HARBORS",
            "SILVER LAKES RV RESORT AND GOLF CLUB",
            "CROWN COLONY",
            "MCPHIE PARK",
            "CABANA CITY",
            "BONITA FAIRWAYS",
            "CAPE ROYAL",
            "SHOREHAVEN ESTATES",
            "BAYSHORE ESTATES SUBDIVISION",
            "PALMETTO PALMS R V",
            "TARPON BAY",
            "ESPLANADE BY THE ISLANDS",
            "ROOKERY POINTE",
            "CANDLEWOOD LAKE ESTATES",
            "NUTMEG VILLAGE",
            "HOLLY TERRACE",
            "GOLDEN GATE",
            "TIDEWATER ISLAND",
            "WILDBLUE",
            "BANYAN WOODS",
            "POINSETTIA PARK MOBILE HOME CO-OP INC",
            "OAKES ESTATES",
            "THE EGRET",
            "SEA ISLES",
            "THE COVE",
            "MARINERS COVE",
            "AVE MARIA",
            "YACHT CLUB",
            "FORT MYERS BEACH CAMPGROUND",
            "WINDING CYPRESS",
            "HIGH POINT PLACE",
            "SEVEN LAKES",
            "AUDUBON",
            "TWIN EAGLES",
            "BARDEN SUBDIVISION",
            "HICKORY POINTE",
            "CAPE COLONY CONDO",
            "SCHOONER BAY COLUMBIA",
            "KINLEYLAND",
            "COOPERS PARK",
            "IMPERIAL WILDERNESS",
            "CAPTIVA PALMA UNRECORDED SUBDIVISION",
            "GRAND OLE MAN",
            "ST. CHARLES HARBOUR",
            "SAN MATEO",
            "SANIBEL SURFSIDE CONDO",
            "ENTRADA",
            "BANYAN BAY",
            "LEELAND HEIGHTS",
            "ISLAND WALK",
            "LAKE TRAFFORD",
            "LEISURE TIME CAMPSITES",
            "TARPON COVE",
            "TURNER OAK HILL ESTATES",
            "REFLECTION LAKES COMMERCIAL CENTER",
            "MERCATO",
            "TROPIC TERRACE",
            "CORKSCREW SHORES",
            "WESTBROOK",
            "ARROYAL HEIGHTS",
            "MOON LAKE",
            "FOXMOOR",
            "BONITA BEACH PLANTATION HOUSE",
            "ALABAMA GROVE TERRACE",
            "TAMIAMI VILLAGE",
            "CINNAMON COVE",
            "CROSS CREEK COUNTRY CLUB",
            "KELLY GREENS GOLF AND COUNTRY CLUB",
            "HARBOUR ISLE YACHT AND RACQUET CLUB CONDO",
            "DEEP CREEK",
            "VERANDAH",
            "PALMETTO COVE",
            "SAN CARLOS ESTATES",
            "THE FORUM",
            "BRECKENRIDGE",
            "LAKE PARK",
            "NAPLES HEIGHTS",
            "MEADOWBROOK ESTATE",
            "LAKEWOOD",
            "PINE RIDGE OF FORT MYERS VILLAGE",
            "LITTLE HICKORY BAY",
            "WILLOUGHBY ACRES",
            "OAKWOOD",
            "WESTWOOD ACRES",
            "HIGHLAND PARK EAST",
            "GOLDEN ACRES",
            "CYPRESS WOODS ESTATES",
            "LIVINGSTON WOODS",
            "CRANBROOK HARBOR",
            "GORES A M SUBD",
            "ATRIUM CONDO",
            "GREYHAWK AT GOLF CLUB OF THE EVERGLADES",
            "COLONIAL ACRES UNIT 2",
            "VIZCAYA VILLAS UNREC",
            "BEACH AND TENNIS CLUB",
            "LEHIGH PARK",
            "MAGNOLIA LANDING",
            "GENOVA",
            "BONAIR",
            "GATEWAY",
            "BOTANICA LAKES",
            "THE COVE AT SIX MILE",
            "BONITA PINES",
            "MAPLE GARDENS",
            "SOUTHWEST LEHIGH",
            "FLORIMOND MANOR",
            "ESTERO SPRINGS",
            "SUBURBAN PARK",
            "BAYSHORE HEIGHTS",
            "RIDGEWOOD PARK",
            "STORTER",
            "HOLEUSA ESTATES",
            "SANDALFOOT CONDOMINIUM",
            "AMERICA OUTDOORS CONDO",
            "HIDEAWAY BEACH",
            "GOODLAND",
            "MAJESTIC",
            "WINDSOR MANOR CONDO",
            "ROYAL WOOD",
            "HORSE CREEK ESTATES",
            "EAGLE RIDGE",
            "THE BROOKS",
            "VILLA MAR BONITA BEACH",
            "WILLIAMS PARK ADD",
            "THE LANDINGS",
            "GREY OAKS",
            "THE HIDEAWAY COUNTRY CLUB",
            "CARVER PARK",
            "WATERWAY ESTATES",
            "CARISSA CONDO",
            "HARBOUR VISTA CONDO",
            "CAMELOT",
            "CITY VILLAGE",
            "CAPE PARKWAY",
            "CORAL BAYVIEW CONDO",
            "PALACO GRANDE",
            "DONOGHUES 2ND SUBD",
            "DELAY PARK",
            "ADMIRALTY YACHT & RACQUET CLUB",
            "BROOKSIDE",
            "FELDA",
            "LAKEPORT",
            "PARKWAY CONDO",
            "RIVER OAK PARK",
            "ISLAND PARK",
            "OLD BONITA",
            "RIVER HARBOR CLUB CONDO",
            "CARRIAGE CIRCLE OF NAPLES",
            "WATERSIDE AT BAY BEACH",
            "TIMBER CREEK",
            "RIVER BY",
            "HIGH POINT",
            "PINE MANOR",
            "BUENA VISTA",
            "WHISPERING PINES",
            "CORALEE CONDO",
            "ROBERTS C F SUBD",
            "ORANGE BLOSSOM ESTATES",
            "BELL TOWER PARK",
            "BENT CREEK PRESERVE",
            "BERKSHIRE VILLAGE",
            "BRIGHTWATER",
            "TAMIAMI ESTATES",
            "BLUE HERON",
            "CASCADES AT ESTERO",
            "OAK RIDGE MANOR",
            "OLD PELICAN BAY",
            "TURTLE LAKE",
            "KAUNES SUBD",
            "SOUTH IMMOKALEE HEIGHTS",
            "COLONIAL FARMS",
            "LAKES OF SAN SOUCI",
            "WINDJAMMER VILLAGE OF NAPLES",
            "BUCKHEAD RIDGE",
            "GRANDEZZA",
            "PUNTA RASSA",
            "RAFFIA PRESERVE",
            "HARLEM",
            "GUAVA GROVE",
            "ROSE GARDEN VILLAS CONDO",
            "WONDERLING PARK",
            "SOUTH HENDRY COUNTY",
            "PARK VIEW CONDO",
            "LAKEWOOD VILLAGE",
            "RIVERWIND COVE",
            "PORTICO",
            "PEBBLEBROOKE LAKES",
            "MARK I",
            "CALOOSA VIEW",
            "POSITANO PLACE",
            "GULFHAVEN",
            "TIMBER RIDGE",
            "CORAL OAKS GOLF COURSE",
            "LAKE KELLY",
            "COLLIER & RUPERT",
            "LAGUNA LAKES",
            "ENBROOK",
            "COURTYARDS OF CAPE CORAL SOUTH",
            "HENDRY CREEK",
            "PALM ACRES",
            "LAUREL OAKS",
            "BELLA VIDA",
            "ISLAND SHORES",
            "PINE ISLAND TROPICAL HOMESITES",
            "RIVERSIDE AVENUE VILLAS",
            "COLONIAL POINTE",
            "AVIANO",
            "TWIN BROOKS ESTATES",
            "GUILFORD ACRES",
            "COCONUT GROVE",
            "CEDAR HAMMOCK",
            "ESPLANADE LAKE CLUB",
            "MYRTLE COVE ACRES",
            "PRIMA LUCE",
            "PINK SHELL",
            "HOLIDAY HEIGHTS",
            "LUCAYA",
            "CAMPBELL ACRES",
            "CHULA VISTA MANOR 1ST ADDN",
            "LEE BLVD TRADE CTR",
            "LIGHTHOUSE BAY AT THE BROOKS",
            "PORTOFINO",
            "BONITA BEACH TRAILER PARK",
            "HOLIDAY CONDO INC",
            "LAKES OF ESTERO",
            "MARBLEBROOK",
            "SIX LAKES COUNTRY CLUB",
            "CYPRESS CAY",
            "RIVER GROVE ESTATES",
            "THE RESIDENCE",
            "PINEHURST ADDITION",
            "VALENCIA COUNTRY CLUB",
            "VALENCIA LAKES",
            "WOODGATE AT NAPLES",
            "SHADOW WOOD PRESERVE",
            "LOVEJOY PARK",
            "THE FOREST",
            "LAKE LOUISE CONDO",
            "CYPRESS CONDO",
            "REGAL POINT",
            "BOWLING GREEN",
            "ARBOR TRACE",
            "THE PALMS OF BAY BEACH",
            "BAYSHORE COMMERCIAL",
            "EL RIO GARDEN CONDO",
            "TIBURON",
            "LOCHMOOR",
            "FOUNTAINS",
            "BERMUDA LINKS",
            "IONA GARDENS",
            "KENSINGTON",
            "HARBORAGE",
            "BONITA VILLAGE",
            "COPPER COVE PRESERVE",
            "BAYSHORE CONDO",
            "CORKSCREW WOODLANDS",
            "CITADEL",
            "WILSHIRE LAKES",
            "BOTANICAL PLACE",
            "LAGUNA SHORES",
            "HEMINGWAY PLACE",
            "OASIS OF FORT MYERS",
            "RIVER HALL",
            "FERNWALK",
            "VILLAGIO",
            "GULF HARBOR",
            "WINDSONG",
            "GULF HEIGHTS",
            "MARBELLA LAKES",
            "BERMUDA LAGO",
            "COUNTRY CLUB OF NAPLES",
            "WIND SONG CONDO",
            "FALLING WATERS BEACH RESORT",
            "GARDENS AT BEACHWALK",
            "SOUTHWINDS ESTATES",
            "WESTMINSTER",
            "THE RESERVE AT ESTERO",
            "LIVINGSTON LAKES",
            "COVE TOWERS",
            "NAPLES GARDENS",
            "NAPLES BAY CLUB",
            "ORANGE RIVER CENTRE",
            "PERIWINKLE PROP SUBD UNREC",
            "EAST GREENS LAND CONDO",
            "INDIAN CREEK",
            "GULF REFLECTIONS",
            "SUMMERLIN VILLAGE CONDO",
            "ARROYAL",
            "REFLECTION ISLES",
            "AVON PARK",
            "MIRAMAR ARMS CONDO",
            "PORT NELL VILLAS",
            "MANATEE BAY UNRECORDED SUBDIVISION",
            "RIVER GARDEN CONDOMINIUM",
            "PINE VIEW VILLAS",
            "FIRANO AT NAPLES",
            "BAYVIEW RANCHETTES",
            "NAPLES 701",
            "HIGHLAND ESTATES",
            "MARIANA HEIGHTS",
            "NAPLES LAKES COUNTRY CLUB",
            "LEXINGTON COUNTRY CLUB",
            "VILLAS OF WHITTENBERG",
            "DEL TURA COUNTRY CLUB",
            "CASA DEL VIDA",
            "LAKERIDGE",
            "LITTLE HARBOUR",
            "HUSCHKA",
            "ORANGE HARBOR MOBILE HOME PARK",
            "FAIRVIEW ISLES",
            "ROTONDA MEADOWS",
            "PARK WEST",
            "DEAUVILLE LAKE CLUB",
            "FLAMINGO PARK",
            "DICKEYS JOHN R SUBD",
            "BENCHMARK CORPORATE PK LT 21",
            "BLUE WATER SHORES",
            "MORSE SHORES",
            "BELMONT",
            "PINECREST",
            "WALSH SUBDIVISION",
            "TARPON BEND UNREC",
            "EAST ENGLEWOOD",
            "RIDGE HARBOR",
            "SOUTH 29 INDUSTRIAL PARK",
            "ST JAMES CITY",
            "BIG OAK ACRES",
            "SEAGRAPE",
            "BELLE VISTA ESTATES UNREC",
            "EAST BAYSHORE",
            "TIMBERBEND SUBD",
            "PUNTA ROBALO UNRECORDED SUBDIVISION",
            "DESOTO COUNTY",
            "BRIGHT WATER",
            "PLACID LAKES",
            "CAROLANDS UNRECORDED SUBDIVISION",
            "CHARLESTON PARK",
            "SERENITY COVE",
            "SPRINGS OF SAN CARLOS",
            "SUNSET NORTH CONDO",
            "TERRA VISTA",
            "CALOOSA BAYVIEW",
            "GATEWAY VILLAS",
            "PIPERS GROVE",
            "INDIAN PINES",
            "TWELFTH STREET PARK",
            "COLLIERS RESERVE",
            "TIDEWATER",
            "RETREAT",
            "BERNWOOD PARK OF COMMERCE",
            "PINEHURST ESTATES",
            "EDGEWOOD SUBD",
            "WHITEHEAD CREEK SUBDIVISION",
            "PALMLEE PARK",
            "EL JOBEAN",
            "PINE ISLAND ESTATES",
            "FAIRWAY ESTATES",
            "RIVER ROYALE",
            "SHELL CREEK HEIGHTS",
            "CHASE SUBDIVISION UNREC",
            "TAMIAMI HEIGHTS",
            "MANATEE POINT",
            "SOUTHEAST LEHIGH",
            "GULF SHORES ESTATES",
            "TERRY TICE + VANDERWALKER",
            "SANIBEL SHORES",
            "BUCKINGHAM AIR PARK",
            "LINCOLN PARK",
            "PINE GROVE TOWNHOUSES",
            "ABACO POINTE",
            "MANDALAY",
            "GARDENS OF BONITA SPRINGS",
            "SMOKEHOUSE KEY",
            "CORKSCREW ESTATES",
            "SCARECROW FARMS",
            "CRYSTAL LAKES",
            "REFLECTION KEY",
            "VILLA SOUTH",
            "INDIAN VILLAGE",
            "ROYAL EAST UNIT 1",
            "DAUGHTREYS CREEK",
            "CYPRESS BEND RV RESORT",
            "PINE ISLAND FILL",
            "ALTAMONT PARK",
            "QUAIL CREEK",
            "EVANSTON PARK CONDO",
            "GLADES HAVEN RESORT AND MARINA",
            "SUNSET POINTE",
            "THE ENCLAVE OF DISTINCTION",
            "DEER RUN FARMS",
            "RUBICON CONDO",
            "VIKING CONDO",
            "LAKE PLACID WATERWAY",
            "GULF ISLAND MANOR",
            "PINE LAKES COUNTRY CLUB",
            "TEE AND GREEN ESTATES",
            "MORNINGSIDE",
            "ROCK HARBOR",
            "NAPLES MANOR",
            "GULFSIDE",
            "FT MYERS VILLAS",
            "CAPE MARCO",
            "RENAISSANCE VILLAGE",
            "SUNWARD CONDO",
            "THE COLONY",
            "MATLACHA ISLES",
            "VERONA WALK",
            "PLAN OF RIVERSIDE",
            "SUN-N-FUN MOBILE HOME VILLAGE",
            "CARLETON ESTATES",
            "SUNSET LAKE CONDO",
            "STRATFORD PLACE CONDO",
            "ISLES OF PORTO VISTA",
            "FOUR MILE COVE",
            "THE VILLAS AT VENEZIA",
            "TWIN LAKES",
            "HANSONS W STANLEY SUBD",
            "LAUREL ESTATES",
            "TRAILSIDE",
            "TUSCANY COVE",
            "KELLY PLAZA",
            "DROP ANCHOR MOBILE HOME",
            "PALOMA",
            "GULLWING BEACH RESORT",
            "RIVER TERRACE CONDO",
            "GORTONS",
            "BURNT STORE COLONY",
            "MARINER POINTE CONDO",
            "WINDWARD ISLE",
            "EVANS ADDITION",
            "EUROPEAN TOWNHOUSE",
            "BAREFOOT BAY",
            "RIVIERA CLUB",
            "IMPERIAL SHORES",
            "HEITMANS",
            "PERIWINKLE PINES",
            "CAPTAINS BAY",
            "ESTERO BAY SHORES",
            "BEAUMER",
            "VENETIAN POINTE",
            "SAPPHIRE COVE",
            "MANATEE COVE",
            "SURF SONG CONDO",
            "FUNCKS SUBD",
            "POINCIANA VILLAGE",
            "REMINGTON OAKS",
            "FLAGHOLE",
            "TRADEWINDS",
            "MAPLEWOOD",
            "BLACK BEAR RIDGE",
            "VICTORIA COVE CONDO",
            "DAVIS WOODS CONDOMINIUM",
            "IMMOKALEE HIGHLANDS",
            "DUCHESS I CONDO",
            "PINE ISLAND VILLAS",
            "NORTH LABELLE",
            "IMPERIAL HARBOR",
            "ESTERO PARK",
            "CRAIGS SUBDIVISION",
            "DEEP LAGOON ESTATES",
            "LAZY DAYS MOBILE VILLAGE",
            "RIVERS CONDO",
            "CATALINA ISLES",
            "LAKE TRAFFORD ESTATES",
            "ALDEN PINES",
            "HARBOR HEIGHTS CONDO",
            "BONITA SPRINGS GOLF & COUNTRY CLUB",
            "BROOKSHIRE",
            "PALM ISLAND ESTATES",
            "UPPER CAPTIVA",
            "SHALLOWS",
            "AQUA SHORES",
            "CHARLEE RANCHETTES",
            "RIVERSIDE",
            "HEATHER RIDGE",
            "SABAL SPRINGS GOLF AND RACQUET CLUB",
            "QUEENS PARK",
            "CAROLANDS",
            "RIVERVUE PARK",
            "CALUSA BAY SOUTH",
            "SUN TERRACE",
            "HAWK'S PRESERVE",
            "SOUTH POINTE SOUTH",
            "CARILLON WOODS",
            "COCONUT RIVER",
            "CALUSA RIDGE",
            "HILLS T.P.",
            "GROVES",
            "SEA LOFT VILLAGE CONDO",
            "PINE HAVEN CONDO",
            "PELICAN LAKE RV RESORT",
            "SOUTH POINTE VILLAS CONDO",
            "HARBOR ESTATES FIRST ADD",
            "SAND POINTE",
            "BLIND PASS CONDO",
            "TIMBERS",
            "MELALEUCA VILLAGE",
            "GULF SHORES",
            "LEAWOOD LAKES",
            "HOLIDAY MANOR",
            "MCGREGOR VISTA",
            "PALM BEACH LANDINGS",
            "ONE",
            "FOREST LAKE TOWNHOMES",
            "SOUTH BAY PLANTATION",
            "CYPRESS WALK",
            "SUNDIAL OF SANIBEL",
            "FRANKS",
            "RIVER REACH",
            "COCO BAY",
            "PINE ISLAND COVE",
            "ORCHID HARBOUR VILLAS CONDO",
            "TERRA PALMA",
            "CAMDEN SQUARE",
            "COLONNADE AT FORUM",
            "EVEREST CONDO",
            "MAJESTIC PALMS",
            "CAPE GARDENS CONDO",
            "LAKE ARROWHEAD MOB VILLAGE",
            "CYPRESS PRESERVE"
        ].sort(),
        subCondo: '',
        subCondoOptions: [
            "VANDERBILT LAKES",
            "NEWCASTLE",
            "THE DUNES",
            "SANDALWOOD VILLAGE",
            "VALENCIA AT PELICAN BAY",
            "AQUALANE SHORES",
            "NAPLES PARK",
            "CAPE CORAL",
            "OLDE TOWNE CONDO",
            "CHATEAUMERE",
            "MAPLELEAF VILLAS",
            "LAKOYA",
            "SHORE WOODS",
            "NOT APPLICABLE",
            "AVELLINO",
            "MIRASOL AT COCONUT POINT",
            "MALLARDS LANDING",
            "EDGEWATERS GARDENS",
            "RIVER TOWERS",
            "BRIARWOOD",
            "THE PLACE AT CORKSCREW",
            "DAVIS LAKE CONDO",
            "THE PINES",
            "LAUREL OAKS AT PELICAN BAY",
            "SATURNIA LAKES",
            "CALABRIA",
            "SORRENTO VILLAS",
            "OLDE CYPRESS",
            "ST CROIX",
            "HUNTINGTON LAKES",
            "ROYAL ARMS EXTENSION",
            "NAVARRA PARK",
            "THE BARCELONA",
            "SOCE FLATS",
            "LAUREL MEADOW",
            "HERITAGE POINTE",
            "SWEETWATER BAY",
            "STONECREEK",
            "KALEA BAY TOWER 100",
            "BELLA VITA",
            "BABCOCK NATIONAL",
            "IBIS WOODS",
            "BURNT STORE MARINA",
            "MATLACHA",
            "CENTRAL PARK SOUTH CONDOS",
            "SERANO",
            "OLE",
            "LAKEVIEW AT CARLTON LAKES",
            "VANDERBILT SHORES",
            "SURFSIDE CLUB AT COQUINA SANDS",
            "BONITA NATIONAL GOLF AND COUNTRY CLUB",
            "OLDE NAPLES",
            "SEYCHELLES",
            "BILTMORE AT BAY COLONY",
            "CALOOSA ISLES II CONDO",
            "PRESTWICK PLACE",
            "LEHIGH ACRES",
            "PROVINCETOWN",
            "CASA BONITA II",
            "RAVENNA",
            "NAPLES HIDEAWAY CLUB",
            "VILLAGES AT COUNTRY CREEK",
            "PRIVATEER OF FT MYERS BEACH",
            "FAIRWAYS",
            "CHESAPEAKE MANOR",
            "HERITAGE LANDING GOLF AND COUNTRY CLUB",
            "DEL MAR",
            "EAGLE CREEK",
            "ST NICOLE",
            "ESPLANADE AT HACIENDA LAKES",
            "VILLA DANNA",
            "RIVERBEND MOTORCOACH RESORT",
            "MARCO ISLAND",
            "SEASONS AT NAPLES CAY",
            "DONAX VILLAGE CONDO",
            "BERMUDA COVE",
            "EVERGLADES TOWN",
            "GOLDEN GATE ESTATES",
            "KEY MARCO",
            "TURTLE POINT COVE",
            "REFLECTION LAKES",
            "ROYAL PALM GOLF ESTATES",
            "ST VINCENTS",
            "SEASONS AT BONITA",
            "SORRENTO",
            "BONITA FARMS",
            "PORT CHARLOTTE",
            "PORT LABELLE",
            "COPPER OAKS",
            "COMPASS POINT SOUTH",
            "PEBBLE CREEK",
            "VANDERBILT SURF COLONY",
            "PRINCETON PLACE",
            "VILLAGES AT EMERALD BAY",
            "ST MARISSA",
            "REGATTA",
            "EAGLEWOOD",
            "ESPLANADE CLUB",
            "GRANDE PHOENICIAN",
            "NEW SUBDIVISION",
            "TUSCANY GARDENS",
            "VILLAGE WALK OF BONITA SPRINGS",
            "SANDPIPER ISLE",
            "ADMIRALTY POINT",
            "ST SIMONE",
            "GULF BREEZE AT VANDERBILT",
            "NAPLES SANDPIPER BAY CLUB",
            "L'AMBIANCE",
            "CRESCENT",
            "PAVILION CLUB",
            "VIANSA",
            "SARATOGA COLONY",
            "PROVENCE",
            "JASPER",
            "EAGLE COVE",
            "ORCHARDS",
            "VANDERBILT VILLAS",
            "GREENLINKS",
            "TERRACE",
            "BARRINGTON CLUB",
            "NAPLES COVE",
            "FAIRWAYS AT EMERALD GREENS",
            "BRIDGEWATER BAY",
            "LUGANO",
            "ARIELLE",
            "BAY WOODS",
            "MARQUESA AT BAY COLONY",
            "CARAWAY LAKES",
            "BEACH WALK CONDO",
            "HOLLY GREENS VILLA",
            "CAY LAGOON",
            "LALIQUE",
            "PARK SHORE",
            "MARCO BEACH",
            "TIMBERCREEK",
            "BRITANNIA I",
            "MONTE CARLO CLUB",
            "CYPRESS GLEN",
            "FURSE LAKES",
            "VANDERBILT GULFSIDE",
            "ST TROPEZ",
            "MANSION HOUSE",
            "IMPERIAL GARDENS",
            "MONTENERO",
            "LAS BRISAS AT SPANISH WELLS",
            "WILLOWBROOK",
            "FORT DENAUD ACRES UNIT 2",
            "AZURE AT HACIENDA LAKES",
            "VILLAS OF PARK SHORE",
            "VERANDAS AT TIGER ISLAND",
            "COLONADE",
            "PAVIA",
            "ISLAND COVE OF CAPE CORAL",
            "ISLES OF COLLIER PRESERVE",
            "TURNBERRY",
            "ACREAGE HEADER",
            "KEEWAYDIN ISLAND",
            "RIVERWOOD",
            "REGENCY RESERVE",
            "INDIGO LAKES",
            "COUNTRY CLUB ESTATES",
            "FLAMINGO FAIRWAYS II",
            "BUTTONWOOD KEY",
            "BONITA SHORES",
            "LAGUNA ROYALE",
            "STELLA MARIS",
            "ARTESIA",
            "GLENEAGLES",
            "BONITA BEACH CLUB",
            "HIDEAWAY HARBOR",
            "HERITAGE BAY",
            "THE SEVILLE",
            "COQUINA SANDS",
            "SAIL HARBOUR",
            "GRANDE CAY",
            "RESERVE AT NAPLES",
            "VANDERBILT BEACHCOMBER",
            "SOLAMAR",
            "MIRASOL",
            "PUNTA GORDA",
            "COACH HOMES AT HERITAGE BAY",
            "LA MER",
            "LAUREL GREENS",
            "TRIESTE AT BAY COLONY",
            "ASCOT",
            "GRANDE DOMINICA",
            "BELLERIVE",
            "NORTH STAR YACHT CLUB",
            "SANIBEL VIEW CONDO",
            "FOREST LAKES GOLF AND TENNIS CLUB",
            "SOUTH GULF COVE",
            "TARPON VILLAGE APTS",
            "ROTONDA MEADOWS",
            "WHEELERS SUBD",
            "THE RESIDENCES AT COCONUT POINT",
            "ACREAGE",
            "FORT MYERS",
            "MARIANA PARK",
            "CHARLOTTE SHORES",
            "EL DORADO ACRES",
            "HIGHLAND ESTATES UNRECORDED SUBDIVISION",
            "CALOOSA HAMMOCK",
            "LAKEVILLE",
            "NORTH FORT MYERS",
            "SEABREEZE SOUTH",
            "FOXWOOD",
            "MCGREGOR ESTATES",
            "SUNCOAST ESTATES UNREC",
            "ESTATES",
            "LABELLE",
            "PINE ISLAND CENTER",
            "SHANNONS",
            "MOORE HAVEN",
            "SAN CARLOS PARK",
            "ALVA",
            "MILLERS PARK",
            "LABELLE ESTATES",
            "SUNSET CAY VILLAS",
            "BONITA SPRINGS",
            "BURNT STORE LAKES",
            "CORDERA",
            "MONTURA RANCH ESTATES",
            "SUNCOAST ESTATE",
            "NAPLES SQUARE",
            "TROPICAL GULF ACRES",
            "PALM BAY ESTATES",
            "RUSSELL PARK",
            "SONOMA",
            "WORLD TENNIS CENTER",
            "BEACH HOMES",
            "MARGARET ACRES",
            "COUNTRYSIDE CONDOS",
            "HUNTERS RIDGE",
            "CONTESSA AT BAY COLONY",
            "CYPRESS TRACE",
            "BEACHWALK VILLAS",
            "VERONA LAGO",
            "CITRUS SPRINGS",
            "NORTH PORT",
            "BURNT STORE MEADOWS",
            "KREAMERS AVOCADO SUBD",
            "GREENBRIAR",
            "LAKE MUREX",
            "DOVER PARC",
            "TIMBER TRAILS",
            "GULF COVE",
            "PINE ISLAND RIDGE",
            "BUCKINGHAM",
            "ROTONDA SANDS",
            "GRACIOUS HOMES SUBD",
            "NORTH CAPTIVA DUNES",
            "RIVERCREEK",
            "TOWN AND RIVER",
            "METES AND BOUNDS",
            "BAYVIEW ACRES",
            "REGENT PARK",
            "SUTTON CAY",
            "SANCTUARY AT WULFERT",
            "NORTH BELLE MEADE",
            "VANDERBILT TOWERS",
            "MYSTIC GREENS",
            "TUCKAWEYE",
            "PINE RIDGE",
            "RIALTO",
            "PINEWATER PLACE",
            "NORTH LABELLE GLADES",
            "STONEYBROOK",
            "FOUNTAIN LAKES",
            "LEILANI",
            "CAPE CORAL - LEE COUNTY INDUSTRIAL PARK",
            "CORAL HARBOR",
            "PLANTATION ISLAND",
            "CROWN POINTE SHORES",
            "MERIDIAN CLUB",
            "BAREFOOT BEACH CLUB",
            "PARK SHORE RESORT",
            "GULF ACRES",
            "COLONIAL COUNTRY CLUB",
            "BEARS PAW",
            "AVALON",
            "VANDERBILT LANDINGS",
            "BAREFOOT PELICAN",
            "SANDY LANE",
            "CONCORDIA",
            "PLAYERS COVE",
            "BUCKINGHAM PARK",
            "SOUTH SEAS CLUB CONDO",
            "BELLAMAR",
            "OAKWOOD VILLAS",
            "VISTAS AT PARK SHORE",
            "MOORINGS",
            "TIMARRON",
            "DELASOL",
            "SURFSEDGE",
            "CONNERS",
            "WIGGINS LAKES AND PRESERVES",
            "VILLAS ENCANTADA",
            "TROPHY CLUB",
            "CLARIDGE",
            "KNIGHTS BOKEELIA ISLE",
            "TRA VIGNE",
            "ELEVEN HUNDRED CLUB",
            "OAKWOOD",
            "EXECUTIVE CLUB",
            "GRANDE EXCELSIOR",
            "HIDEAWAY BEACH",
            "COLONIAL LINKS",
            "PARK SHORE TOWER",
            "ST MAARTEN",
            "SARATOGA",
            "YACHT HARBOR MANOR",
            "LEHIGH ESTATES",
            "CONCORD",
            "Vanderbilt Villas",
            "MARINER APTS MARCO ISLAND",
            "PALM COLONY",
            "SHERRILL POINT",
            "THE ENCLAVE AT NAPLES",
            "NAPLES CLUB ESTATES",
            "EAGLE CREEK VILLA HOMES",
            "KENSINGTON GARDENS",
            "GULF SOUTH",
            "BAYFRONT",
            "SEAWATCH",
            "BONITA BEACH",
            "WHISKEY CREEK",
            "MOODY RIVER ESTATES",
            "SIENA",
            "NEWPORT MANORS CONDO",
            "COACH HOUSE",
            "RIVERSIDE CLUB",
            "ESPLANADE",
            "BERMUDA POINTE",
            "FOUR SEASONS",
            "NAPLES CONTINENTAL",
            "SAVOY",
            "SEASCAPE",
            "GLENCOVE",
            "NAVONA AT THE COLONY",
            "FOREST LAKES",
            "BRIDGETOWN",
            "CALUSA BAY NORTH",
            "INDIAN WELLS GOLF VILLAS",
            "LAKESIDE CARRIAGE HOMES",
            "CHATEAU SUZANNE",
            "MEADOWLARK ESTATES",
            "HARBORSIDE TERRACE",
            "SOUTH POINTE WEST CONDO",
            "FORT MYERS SHORES",
            "MANATEE COVE CONDO",
            "TRIESTE",
            "CHERRY ESTATES",
            "HARBOURTOWNE CONDO",
            "MUSTANG ISLAND",
            "PALM BEACH LANDINGS",
            "PORT ROYAL",
            "ANA'S PLACE",
            "NAPLES BATH AND TENNIS CLUB",
            "BONITA ISLES",
            "WATERFORD AT WORTHINGTON",
            "GULF REFLECTIONS",
            "MAJORS",
            "TERRACE VI",
            "PELICAN RIDGE",
            "WEDGE WOOD AT THE STRAND",
            "RIVERSTONE",
            "CASTALINA",
            "CARRINGTON",
            "ASCOT AT LELY RESORT",
            "ST KITTS",
            "GULF VIEW BEACH CLUB",
            "NORTHSHORE LAKE VILLAS",
            "BRIDGEWATER",
            "MONACO BEACH CLUB",
            "ISLAND BREEZE",
            "BELLA FIRENZE",
            "STRATFORD PLACE",
            "PELICAN MARSH",
            "THE CARLYSLE",
            "ST JAMES CITY",
            "NAPLES IMP CO LITTLE FARMS",
            "ROTONDA LAKES",
            "SHELL HARBOR",
            "PALMETTO PINES COUNTRY CLUB",
            "INDIAN HILLS",
            "JOSE'S HIDEAWAY",
            "LEHIGH PROPERTIES",
            "MARION OAKS",
            "PUNTA GORDA ISLES",
            "HARBOR HEIGHTS",
            "CHARLOTTE RANCHETTES",
            "BANYAN VILLAGE",
            "RIVERBEND",
            "ISLAND OF HAPPINESS",
            "BURNT STORE VILLAGE",
            "SERATA",
            "BAYVIEW PARK",
            "SHOREHAVEN ESTATES",
            "OLD FORT DENAUD",
            "ADMIRAL LEHIGH ESTATES",
            "WEST LEHIGH",
            "KREAMERS AVOCADO UNREC",
            "SOUTHWOOD",
            "LEELAND HEIGHTS",
            "ALDEN ACRES UNRECORDED SUBDIVISION",
            "CASTAWAY KEY UNRECORDED SUBDIVISION",
            "RIDGEVIEW ESTATES",
            "ROTONDA VILLAS",
            "PAGE PARK",
            "MIRROR LAKES",
            "LEISURE ACRES",
            "FRANK C ADAMS SUBDIVISION UNRECORDED SUBDIVISION",
            "JONATHAN HARBOUR",
            "PIONEER PLANTATION SEC 35",
            "NORTH LABELLE",
            "MONTURA RANCH SEC 14",
            "USEPPA ISLAND",
            "PINE ISLAND",
            "SUNDIET VILLAGE",
            "WILDCAT FARMS",
            "CALOOSA ESTATES UNIT 3",
            "GULF HAVEN",
            "CAPE ROMANO",
            "CHANTECLAIR MAISONETTES",
            "PINEHURST",
            "ALTA MAR",
            "PIONEER PLANTATION",
            "BEACHVIEW COUNTRY CLUB ESTATES",
            "PIONEER PLANTATION SEC 22",
            "CASA BONITA ROYALE",
            "SANIBEL HARBOURS",
            "KREAMERS SUBD",
            "WHOLESALE PARK",
            "SOUTH PUNTA GORDA HEIGHTS",
            "CLEWISTON",
            "MONTURA",
            "900 BUILDING",
            "CAPTAINS COVE",
            "PINE ISLAND SHORES UNIT 5",
            "COPELAND VILLAGE",
            "GERBER GROVES SEC 2",
            "DEVONWOOD",
            "MONTEVERDI",
            "PIRATE HARBOR",
            "HERONS GLEN",
            "HICKEY CREEKSIDE",
            "LAMORADA",
            "VENETIAN BAYVIEW",
            "WEST BAY CLUB",
            "BAY POINTE YACHT & RACQUET CLUB",
            "DI NAPOLI",
            "HUNTINGTON LAKES II",
            "LAKE FAIRWAYS COUNTY CLUB",
            "MIRAVISTA",
            "TERRACES AT PARK SHORE",
            "BERKSHIRE LAKES",
            "WORTHINGTON WAY",
            "DORCHESTER",
            "CHIASSO",
            "CAPE HARBOUR",
            "COCONUT BAY",
            "INTERLACHEN",
            "GARDEN LAKES",
            "ANDALUCIA",
            "ALEXANDRA",
            "GRAND CYPRESS I",
            "LAKESIDE GARDENS",
            "VANDERBILT YACHT RACQUET",
            "VALENCIA BONITA",
            "OAKES ESTATES",
            "DIAMOND",
            "AVON PARK",
            "FLORENCIA",
            "VERONA WALK",
            "DEAUVILLE LAKE CLUB",
            "SONSETTE",
            "VILLAS",
            "TANGLEWOOD",
            "OAKMONT",
            "SAN REMO",
            "CARRIAGE HOMES AT LIVINGSTON LAKES",
            "BOLERO AT TIBURON",
            "BREAKWATER",
            "TERRABELLA",
            "MARENGO",
            "BERMUDA CAYS",
            "TURTLE LAKE GOLF COLONY",
            "HYDE PARK",
            "BEAUMER",
            "ADDISON RESERVE",
            "BELLAVISTA",
            "WINDING STREAM",
            "COLONIAL SHORES",
            "MASTERS RESERVE",
            "PASEO",
            "TREVI",
            "LONGSHORE LAKE",
            "LAKESIDE",
            "TAMIAMI VILLAGE",
            "SHERWOOD",
            "DEL VERA COUNTRY CLUB",
            "MATERA",
            "BERMUDA CLUB CONDO",
            "COTTAGE POINT UNREC",
            "MARQUESA ISLES OF NAPLES",
            "HIDDEN LAKES AT WOODS EDGE",
            "DEER CROSSING",
            "HAMILTON PLACE",
            "FOREST VILLAGE",
            "GIAVENO",
            "LITTLE HICKORY SHORES",
            "EL SOL",
            "ISLANDS END",
            "LAKE TIMBER",
            "SANCTUARY",
            "RIVERS REACH",
            "BRITANNIA IV",
            "VILLAGES AT EMERALD LAKES",
            "OASIS",
            "NAPLES BAY RESORT",
            "OXFORD VILLAGE",
            "ELEVEN ELEVEN CENTRAL",
            "GATOR CIRCLE",
            "CASCADA",
            "SAVONA",
            "CASORIA",
            "OLD MARCO VILLAGE",
            "SAFETY HARBOR CLUB",
            "SAN CARLOS PARK GOLF COURSE ADDITION",
            "RIVER FOREST",
            "PALMONA PARK",
            "COMPASS LANDING",
            "MONTURA RANCH SEC 24",
            "ARBORWOOD PRESERVE",
            "ST ANDREWS VERANDAS",
            "BARLETTA",
            "SWEET BAY AT SHADOW WOOD",
            "HALLENDALE",
            "THE HAMPTONS",
            "COTTESMORE",
            "CARLYSLE AT BAY COLONY",
            "WEDGEWOOD",
            "ROYAL HARBOR",
            "MILLBROOK",
            "CASA BONITA I",
            "MARBELLA ISLES",
            "MASTIQUE",
            "PEBBLE SHORES",
            "OPAL",
            "PALERMO",
            "WHISPER TRACE",
            "PARTRIDGE POINTE",
            "ALBERI ACQUA",
            "ST LAURENT",
            "GREENGATE",
            "JASMINE BAY NORTH",
            "RIVERWALK COVE",
            "RICHARDSONS O L SUBD",
            "HAWK'S NEST",
            "BEACH BREEZE",
            "ESTUARY AT GREY OAKS",
            "BEACHWALK GARDENS",
            "GOLDEN GATE CITY",
            "DEEP CREEK",
            "GRAND PINES",
            "BEACHWALK HOMES",
            "SUNNY GROVE",
            "TRIPLE R ACRES",
            "WINDING CYPRESS",
            "CHARDONNAY",
            "PIERRE CLUB",
            "EGRETS WALK",
            "BAYSHORES",
            "MUSTANG VILLAS",
            "SEASCAPE CONDO",
            "HALFMOON POINT",
            "PORT AU VILLA",
            "BURNING TREE",
            "RIDGE LAKE",
            "LOGAN WOODS",
            "BARBADOS",
            "ROSEWOOD",
            "GOLDEN SHORES",
            "LA SCALA AT VANDERBILT BEACH",
            "PONZIANE",
            "CAYMAN",
            "VIA VENETO",
            "CASA BONITA GRANDE",
            "AMBER",
            "SEA CHASE",
            "COCONUT SHORES",
            "CALOOSA PRESERVE",
            "IMMOKALEE ANCHORAGE",
            "ADMIRALS WALK",
            "LINDSFORD",
            "VANDERBILT BAY",
            "DIXON PARK",
            "ONYX TOWNHOME VILLAS",
            "VANDERBILT BEACH AND HARBOUR",
            "PALMETTO POINT",
            "MCGREGOR ISLES",
            "LA PERLE",
            "PARQUE DE LEON",
            "400 LA PENINSULA",
            "WEBER WOODS",
            "ANTILLES",
            "MARINA BAY",
            "PELICAN BAY WOODS",
            "NAPLES BETTER HOMES",
            "MANGROVE BAY",
            "COTTAGE COLONY WEST CONDO",
            "MCGREGOR GARDENS",
            "VILLA PINES",
            "GULFCOAST INN OF NAPLES",
            "SILVER LAKES",
            "EAST ENGLEWOOD",
            "LONG MEADOW",
            "BRIARCLIFF",
            "NORTH RIVER ESTATES",
            "GRANDE ISLE III",
            "HARBOR TOWERS",
            "NEW WATERFORD",
            "HIDDEN LAKES",
            "PIPERS POINTE",
            "IBIS COVE",
            "HAWKSRIDGE",
            "SPINEL",
            "NEAPOLITAN CLUB",
            "GLADES COUNTRY CLUB",
            "IBIS CLUB INTERNATIONAL",
            "COACH HOMES",
            "FOREST PARK",
            "THE SHORES",
            "RUBY AT SUNSTONE",
            "ISLAND HARBORS",
            "PINE ISLAND ESTATES",
            "SONOMA LAKE",
            "BOTANICA LAKES",
            "LOVERS KEY BEACH CLUB",
            "Cape Coral",
            "EAST BAYSHORE",
            "OYSTER BAY",
            "IMPERIAL GOLF ESTATES",
            "BIG CYPRESS GOLF COUNTRY CLUB",
            "MAGNOLIA LANDING",
            "GENOVA",
            "LEXINGTON COUNTRY CLUB",
            "COCONUT CREEK",
            "BAY COLONY SHORES",
            "BAY VILLAS",
            "BERMUDA LINKS",
            "BARRINGTON AT PELICAN BAY",
            "LAKEWOOD",
            "ISLAND ACRES",
            "BONAIR",
            "BRISTOL PARC",
            "DEEP LAGOON ESTATES",
            "GREYHAWK AT GOLF CLUB OF THE EVERGLADES",
            "TOWER POINTE AT ARBOR TRACE",
            "BELLA TERRA",
            "FLORIDA HENDRY LAND TRACTS",
            "COASTAL ESTATES",
            "HIGH POINT PLACE",
            "IONA GARDENS",
            "IMPERIAL WILDERNESS",
            "VILLAS AT PELICAN BAY",
            "SPRING CREEK VILLAGE",
            "CANOPY",
            "APOLLO",
            "OAK STREET UNREC",
            "HIGH POINT COUNTRY CLUB",
            "PALAZZO",
            "EMERSON PARK",
            "HARBORAGE",
            "CRAIGS SUBDIVISION",
            "SILVERWOOD",
            "CAMILLE GARDENS",
            "LAKEWOOD VILLAS",
            "ADMIRAL'S ISLE",
            "FISHERMANS WHARF CONDO",
            "BAYSHORE ESTATES SUBDIVISION",
            "PALMETTO PALMS R V",
            "BIMINI BAY",
            "STERLING GREENS",
            "ESPLANADE BY THE ISLANDS",
            "HEATHERSTONE",
            "ANTIGUA",
            "CANDLEWOOD LAKE ESTATES",
            "NUTMEG VILLAGE",
            "HOLLY TERRACE",
            "COMMODORE CLUB",
            "LANDING",
            "LUCAYA CAY",
            "FAIRWAYS AT PAR TWO",
            "TIDEWATER ISLAND",
            "VISTA WILDBLUE",
            "BANYAN WOODS",
            "POINSETTIA PARK MOBILE HOME CO-OP INC",
            "SERENDIPITY",
            "CERCINA",
            "GULFVIEW APTS OF MARCO ISLAND",
            "TWO BY TWO",
            "THE EGRET",
            "SEA ISLES",
            "THE COVE",
            "JASMINE POINTE",
            "MARINERS COVE",
            "PARADISE VILLAGE AT MARCO BEACH",
            "MONTURA RANCH SEC 27",
            "YACHT CLUB COLONY",
            "DORADO AT FIDDLER'S CREEK",
            "JACARANDA",
            "DEL WEBB",
            "YACHT CLUB",
            "SEAGLASS AT BONITA BAY",
            "FORT MYERS BEACH CAMPGROUND",
            "SEVEN LAKES",
            "AUDUBON COUNTRY CLUB",
            "TWIN EAGLES",
            "DOLPHIN WAY",
            "CAPE COLONY CONDO",
            "SOMERVILLE",
            "FOREST HILLS",
            "SCHOONER BAY COLUMBIA",
            "ASHTON PLACE",
            "KINLEYLAND",
            "COOPERS PARK",
            "CALDECOTT",
            "CASCADES",
            "CAPTIVA PALMA UNRECORDED SUBDIVISION",
            "PAR ONE",
            "GRAND OLE MAN",
            "PARADISE SHORES",
            "HIDDEN LAKE VILLAS",
            "ST. CHARLES HARBOUR",
            "SAN MATEO",
            "SANIBEL SURFSIDE CONDO",
            "ENTRADA",
            "BANYAN BAY",
            "GRANDVIEW",
            "ISLAND WALK",
            "ARROWHEAD RESERVE",
            "EAGLE CAY",
            "LEISURE TIME CAMPSITES",
            "MARTINIQUE",
            "LAKEMONT COVE",
            "CASTELLA",
            "POINTE AT PELICAN LANDING",
            "CAVENDISH COURT",
            "TURNER OAK HILL ESTATES",
            "REFLECTION LAKES COMMERCIAL CENTER",
            "THE STRADA",
            "HARBORSIDE WEST",
            "ST RAPHAEL",
            "VILLAS AT QUAIL RUN",
            "BONITA FAIRWAYS",
            "SOUTH SEAS",
            "TROPIC TERRACE",
            "CORKSCREW SHORES",
            "WESTBROOK",
            "ARROYAL HEIGHTS",
            "SOUTH BEACH CLUB",
            "LAGUNA",
            "TOWN MANOR",
            "MIRAMAR",
            "PALM RIVER ESTATES",
            "ARBORS AT PELICAN MARSH",
            "MOON LAKE",
            "ARBOR LAKES CONDO",
            "BELLINI",
            "SANDOVAL",
            "BONITA BEACH PLANTATION HOUSE",
            "FLAMINGO VILLAGE HOMES",
            "ALABAMA GROVE TERRACE",
            "VILLAGE WALK",
            "LEESURE VILLAGE",
            "Cinnamon Cove",
            "CROSS CREEK COUNTRY CLUB",
            "Terrace",
            "KELLY GREENS",
            "HARBOUR ISLE YACHT AND RACQUET CLUB CONDO",
            "GARDENS AT BERMUDA LINKS",
            "AMBLEWIND",
            "PALMETTO COVE",
            "SAN CARLOS ESTATES",
            "PROMENADE",
            "GREENWOOD VILLAGE AT BRECKENRIDGE",
            "LELY ISLAND ESTATES",
            "Runaway Bay",
            "BANYAN CLUB",
            "LAKE PARK",
            "SALERNO AT BAY COLONY",
            "NAPLES HEIGHTS",
            "ALLEGRO",
            "LE CIEL VENETIAN TOWER",
            "MEADOWBROOK ESTATE",
            "WINTERPARK",
            "ISLES OF CAPRI",
            "PINE RIDGE OF FORT MYERS VILLAGE",
            "VANDERBILT PLACE",
            "TEN MILE ANCHORAGE",
            "RIVER TOWERS CONDO",
            "ORANGE BLOSSOM RANCH",
            "ENCLAVE",
            "EAST STADLER FARMS",
            "KINGWOOD GARDEN",
            "WHISKEY POINTE",
            "ROOKERY POINTE",
            "LITTLE HICKORY BAY",
            "GRAMAC",
            "WILLOUGHBY ACRES",
            "WESTWOOD ACRES",
            "HIGHLAND PARK EAST",
            "GOLDEN ACRES",
            "CYPRESS WOODS ESTATES",
            "GULFSIDE",
            "LIVINGSTON WOODS",
            "TAMARIND CAY",
            "GULF HEIGHTS",
            "VILLA VIZCAYA",
            "DANFORTH LAKES",
            "CRANBROOK HARBOR",
            "SOUTHPOINTE YACHT CLUB",
            "GORES A M SUBD",
            "LELY PINES",
            "DEERWOOD",
            "BURTWOOD",
            "WHEELERS H L SUBD",
            "HENDERSON CREEK PARK",
            "CORONADO",
            "ISOLA BELLA",
            "THE NATIONAL GOLF & COUNTRY CLUB AT AVE MARIA",
            "FAIRMONT",
            "ATRIUM CONDO",
            "ST JUDE HARBORS",
            "BUTTONWOOD HARBOR",
            "COLONIAL ACRES UNIT 2",
            "VIZCAYA VILLAS UNREC",
            "BEACH AND TENNIS CLUB",
            "FLAMINGO FAIRWAYS",
            "LEHIGH PARK",
            "TARPON LANDINGS",
            "THE COVE AT SIX MILE",
            "BONITA PINES",
            "MAPLE GARDENS",
            "MAPLE RIDGE",
            "SOUTHWEST LEHIGH",
            "FLORIMOND MANOR",
            "ESTERO SPRINGS",
            "SUBURBAN PARK",
            "BELLERA WALK",
            "BAYSHORE HEIGHTS",
            "RIDGEWOOD PARK",
            "STORTER",
            "WILDCAT COVE",
            "HOLEUSA ESTATES",
            "PARKSIDE",
            "GOLDEN GATE PROF BLDG",
            "HAMPTON PARK",
            "BEACHMOOR",
            "555 ON FIFTH",
            "LARGO",
            "TIMBER CREEK",
            "SAGAMORE COURT",
            "HARBOUR LANDINGS",
            "WINDSOR MANOR CONDO",
            "BEACH ESTATES",
            "CAPE PARKWAY",
            "OAKMONT VILLAGE",
            "CARVER PARK",
            "WATERWAY ESTATES",
            "DELAY PARK",
            "WATERSIDE AT BAY BEACH",
            "OKEECHOBEE",
            "RIVER BY",
            "RIVER HARBOR CLUB CONDO",
            "CORAL BAYVIEW CONDO",
            "CITY VILLAGE",
            "PALACO GRANDE",
            "DONOGHUES 2ND SUBD",
            "LABELLE RANCHETTES",
            "MYSTIQUE",
            "CARISSA CONDO",
            "ADMIRALTY YACHT & RACQUET CLUB",
            "BROOKSIDE",
            "PARKWOODS TOWNHOUSE COMMUNITY",
            "HOMESTEAD PARK",
            "HARBOUR LIGHTS",
            "RESERVE II",
            "PRIMA LUCE",
            "WINDSOR ACRES",
            "OAKS",
            "RIVER REACH",
            "ROBERT DODDS SUBD",
            "COPPER COVE PRESERVE",
            "SUNNY PALM ESTATES",
            "SEPTEMBER ESTATES AMENDED",
            "ANCHORAGE AT VANDERBILT",
            "PIPERS GROVE",
            "LAKEVIEW TERR",
            "CAMELOT PARK",
            "MUSE",
            "VILLAGES OF STELLA MARIS",
            "CORKSCREW WOODLANDS",
            "WEDGMONT",
            "TOWNHOMES OF SAN SIMEON",
            "SPELLBINDER VILLAS",
            "FEATHER SOUND",
            "GORTONS",
            "CORAL FALLS RESORT",
            "VILLAGES",
            "AVELLINO ISLES",
            "LIGHTHOUSE BAY",
            "LEE COUNTY INDUSTRIAL PARK",
            "YORK MANOR",
            "BERMUDA ISLES",
            "KALEA BAY TOWER 200",
            "MAHOGANY BEND",
            "CLERMONT",
            "CYPRESS LAKES MANOR SOUTH",
            "TERRACE V",
            "BABCOCK",
            "ADMIRALTY HOUSE",
            "SMOKEHOUSE HARBOUR",
            "GULF MANOR CONDO",
            "ERIN LAKE",
            "CLEAVES CORNER UNREC PLAT",
            "ESSEX HOUSE",
            "ROYAL WOOD",
            "EGRET LANDING",
            "ROYAL PALM CLUB",
            "HORSE CREEK ESTATES",
            "FRANCISCAN GARDENS",
            "PEBBLE POINTE",
            "SAWGRASS",
            "PINE MANOR",
            "BUENA VISTA",
            "WHISPERING PINES",
            "CORALEE CONDO",
            "ROBERTS C F SUBD",
            "ORANGE BLOSSOM ESTATES",
            "GERBER GROVES SEC 1",
            "MATERITA",
            "WILLIAMS PARK ADD",
            "VILLA MAR BONITA BEACH",
            "TWIN LAKE ESTATES",
            "MIRADA AT ESTUARY",
            "VENETO",
            "PORTICO",
            "SANDALFOOT CONDOMINIUM",
            "AMERICA OUTDOORS CONDO ASSOCIATION INC",
            "LA GALLERIA",
            "WINDJAMMER VILLAGE AT THE LAND",
            "TWIN PALMS",
            "QUAIL WEST",
            "BRIGHTWATER",
            "ENBROOK",
            "COURTYARDS OF CAPE CORAL SOUTH",
            "EAGLE RIDGE",
            "COUNTRY CLUB MANOR",
            "LAKEWOOD VILLAGE",
            "WINDSOR PLACE",
            "BERMUDA DUNES CONDO",
            "KINGS PORT",
            "RIVERWIND COVE",
            "PEBBLEBROOKE LAKES",
            "RIDGEWOOD OF NAPLES",
            "MARK I",
            "CALOOSA VIEW",
            "POSITANO PLACE",
            "GULFHAVEN",
            "TIMBER RIDGE",
            "CORAL OAKS GOLF COURSE",
            "MCGREGOR VILLAGE CONDO",
            "LAKE KELLY",
            "COLLIER & RUPERT",
            "BEVERLY HILLS",
            "NAPLES CASAMORE",
            "HENDRY CREEK",
            "PALM ACRES",
            "LAUREL OAKS",
            "BELLA VIDA",
            "ISLAND SHORES",
            "JEFFCOTTS WM ADD RESUB",
            "CENTRAL GARDEN",
            "PINE ISLAND TROPICAL HOMESITES",
            "RIVERSIDE AVENUE VILLAS",
            "COLONIAL POINTE",
            "VANDERBILT PALMS",
            "ESTERO COVE CONDO",
            "ARBEL",
            "SPLINTERWOOD",
            "GLENVIEW",
            "HIGHLAND PINES ESTATES",
            "PINE HURST ESTATES",
            "GROVE HEIGHTS",
            "MAGNOLIA ISLES",
            "WILLOW RIDGE",
            "OAK KNOLL AT BONITA BAY",
            "PALMAS DEL SOL",
            "NAPLES TWIN LAKES",
            "SOUTHWINDS APTS OF NAPLES",
            "MARBLEBROOK",
            "SIX LAKES COUNTRY CLUB",
            "LAKE CAMILLE CONDO",
            "CYPRESS CAY",
            "INDIGO PRESERVE",
            "TWIN BROOKS ESTATES",
            "GUILFORD ACRES",
            "AVIANO",
            "CYPRESS LAKE COUNTRY CLUB",
            "MIRADA",
            "RIVER GROVE ESTATES",
            "GOODLAND HEIGHTS",
            "CHULA VISTA MANOR 1ST ADDN",
            "LEE BLVD TRADE CTR",
            "THE RESIDENCE",
            "COCONUT GROVE",
            "GRANADA LAKES",
            "RIVER OAKS",
            "MILANO",
            "SPANISH WELLS",
            "ALDEN WOODS",
            "ESPLANADE LAKE CLUB",
            "WHITE SAND VILLAS",
            "MYRTLE COVE ACRES",
            "KINGS LAKE",
            "FORT MYERS GULF ACRES",
            "PRATO AT PELICAN PRESERVE",
            "VILLAS AT KINGS LAKE",
            "PORTOFINO",
            "HOLIDAY HEIGHTS",
            "SOUTH HENDRY COUNTY",
            "PARK VIEW CONDO",
            "TAMIAMI ESTATES",
            "CUMBERLAND CONDO",
            "COURTYARDS AT GOLDEN GATE",
            "SPERLING",
            "PINEHURST ADDITION",
            "GULLWING CONDO",
            "VALENCIA COUNTRY CLUB",
            "VALENCIA LAKES",
            "PUNTA RASSA",
            "SANDPIPER BEACH CONDO",
            "780 FIFTH AVENUE SOUTH",
            "WOODGATE AT NAPLES",
            "LOVEJOY PARK",
            "PARTRIDGE PLACE",
            "BAY POINTE AT BONITA BAY",
            "POINTE AT PELICAN BAY",
            "LAKE LOUISE CONDO",
            "THE FOREST",
            "CYPRESS CONDO",
            "REGAL POINT",
            "BOWLING GREEN",
            "THE COLONNADE ON 5TH",
            "ARBOR TRACE",
            "FOUR FOUNTAINS",
            "PERIDOT AT SUNSTONE",
            "MANATEE BAY",
            "CALAIS",
            "TOSCANA AT BAY COLONY",
            "FOUNTAINHEAD",
            "ABBEY ON THE LAKE",
            "PINNACLE",
            "WATERCOURSE",
            "RIVERWALK",
            "AMBERLEY COURT",
            "COTTON GREEN",
            "CLUBSIDE RESERVE",
            "SHORE CLUB",
            "THE PALMS OF BAY BEACH",
            "BAYSHORE COMMERCIAL",
            "No Subdivision",
            "El Rio Garden Condo",
            "TWELVE OAKS",
            "LOCHMOOR",
            "HERITAGE GREENS",
            "FOUNTAINS V",
            "PARADOR",
            "LAS PALMAS",
            "WELLINGTON PLACE II",
            "MARSH LANDING",
            "BONITA VILLAGE",
            "SANTA LUCIA",
            "CARRIAGE CIRCLE OF NAPLES",
            "AQUAMARINE AT SUNSTONE",
            "BAYSHORE CONDO",
            "GULF BAY APARTMENTS",
            "VIVALDI",
            "ISLAND CLUB AT CORKSCREW WOODLANDS",
            "FOX CLUB",
            "LONGLAKE",
            "CITADEL SOUTH",
            "WILSHIRE LAKES",
            "SOMERSET AT MOORINGS",
            "PORTO ROMANO",
            "GRAND PRIX APTS",
            "SPOONBILL COVE",
            "CASTILLO AT TIBURON",
            "BOTANICAL PLACE",
            "VILLAGE",
            "ROYAL TEE COUNTRY CLUB ESTATES",
            "LAGUNA SHORES",
            "HAWTHORNE",
            "COTTAGES AT BAREFOOT",
            "HEMINGWAY PLACE",
            "OASIS OF FORT MYERS",
            "ASHTON OAKS",
            "FERNWALK",
            "GULF HARBOUR YACHT & COUNTRY CLUB",
            "VILLAGIO",
            "GULF HARBOUR",
            "WINDSONG",
            "LAKESIDE VILLAS",
            "MARBELLA LAKES",
            "BERMUDA LAGO",
            "NAPLES WALK",
            "SANDPIPER AT BONITA BAY",
            "CASCADES AT ESTERO",
            "WIND SONG CONDO",
            "HEATHERWOOD",
            "FALLING WATERS BEACH RESORT",
            "MARCO TOWERS",
            "BONITA BEACHWALK",
            "PARK SHORE LANDINGS",
            "EMERALD BEACH APARTMENTS",
            "VICTORIA PARK II",
            "FAIRWAY VILLAS",
            "COUNTRY CLUB OF NAPLES",
            "VARENNA",
            "AZURE",
            "MYSTIC RIDGE",
            "IMPERIAL SHORES",
            "EMERALD LAKES",
            "MARBELLA AT SPANISH WELLS",
            "THE GROVES",
            "SANDARAC CONDO",
            "NEVIS AT COVE TOWERS",
            "WESTSHORE AT NAPLES CAY",
            "SUMMERWIND",
            "INDIAN CREEK",
            "OAK BEND",
            "WILD PINES",
            "HIDDEN SANCTUARY VILLAGE",
            "NAPLES MIMOSA CLUB",
            "MONTEBELLO",
            "RIVER GARDEN CONDOMINIUM",
            "LAKE ARROWHEAD",
            "SUMMERLIN VILLAGE CONDO",
            "ARROYAL",
            "CHAMPIONS",
            "SPINDRIFT CLUB",
            "CAPE CORAL COMMERCIAL CENTER",
            "VENTANAS AT TIBURON",
            "MERCATO",
            "NAPLES 701",
            "BEACH CLUB COLONY CONDO",
            "ENGLEWOOD ISLES",
            "MARQUESA ROYALE",
            "SERENA",
            "MCGREGOR RESERVE",
            "CEDAR RIDGE",
            "CASA GRANDE",
            "MEADOWS OF ESTERO",
            "DELA PARK PLACE",
            "FIRANO AT NAPLES",
            "LANCASTER SQUARE",
            "MAPLEWOOD",
            "MARBELLA",
            "CLUB AT NAPLES CAY",
            "WESTGATE AT IMPERIAL GOLF ESTATES",
            "KEY HARBOUR CONDO",
            "MARINA COVE",
            "VINTAGE RESERVE",
            "THE RESIDENCES AT LA PIAZZA",
            "PALM COURT",
            "Bayview Ranchettes",
            "HIGHLAND ESTATES",
            "MARIANA HEIGHTS",
            "HERON CLUB",
            "UPPER CAPTIVA SHORES",
            "SWAN LAKE CLUB",
            "SUN DIAL OF NAPLES",
            "LAKE BARRINGTON",
            "CARENA",
            "WILLOW BROOK AT PELICAN BAY",
            "SOMMERSET VILLAS",
            "CARLTON LAKES",
            "JENNIFER SHORES",
            "VILLAS OF WHITTENBERG",
            "DEL TURA COUNTRY CLUB",
            "WATERFORD",
            "CASA DEL VIDA",
            "ASHLAND",
            "TAMARYND PLACE",
            "LITTLE HARBOUR",
            "MUTINY",
            "HUSCHKA",
            "ORANGE HARBOR MOBILE HOME PARK",
            "Fairview Isles",
            "PARK WEST",
            "FLAMINGO PARK",
            "DICKEYS JOHN R SUBD",
            "GOODLAND ISLES",
            "PORT AU PRINCE",
            "BENCHMARK CORPORATE PK LT 21",
            "SUNCOAST LAKES",
            "BLUE WATER SHORES",
            "MORSE SHORES",
            "FAIRWAY ESTATES",
            "RIVER ROYALE",
            "BIG OAKS ACRES UNIT 2",
            "SEAGRAPE",
            "BELLE VISTA ESTATES UNREC",
            "WALSH SUBDIVISION",
            "PINE VALLEY",
            "TIMBERBEND SUBD",
            "RIDGE HARBOR",
            "LAKE CLUB VILLAS",
            "PUNTA ROBALO UNRECORDED SUBDIVISION",
            "PLACID LAKES",
            "BOCILLA ISLAND CLUB CONDO",
            "BRIGHT WATER",
            "PINECREST",
            "SOUTHERN HEIGHTS",
            "LAKE SUZY",
            "Lehigh Acres",
            "FAIRVIEW ISLES",
            "JEFFCOTTS WM ADD",
            "WINDWARD CAY",
            "MANDALAY",
            "HAWTHORNE ESTATES",
            "HIGHLAND WOODS",
            "BERNWOOD PARK OF COMMERCE",
            "PINEHURST ESTATES",
            "EDGEWOOD SUBD",
            "MONTURA RANCH SEC 35",
            "RAINBOW ESTATES",
            "MONTURA RANCH SEC 36",
            "MC LAIN SUBDIVISION",
            "CAYO COSTA",
            "WHITEHEAD CREEK SUBDIVISION",
            "PALMLEE PARK",
            "WEST WIND ESTATES",
            "EL JOBEAN",
            "INDIAN PINES",
            "TWELFTH STREET PARK",
            "CHATEAU VANDERBILT",
            "COLLIERS RESERVE",
            "TIDEWATER",
            "RETREAT",
            "CORAL RIDGE ESTATES",
            "SHELL CREEK HEIGHTS",
            "CHASE SUBDIVISION UNREC",
            "TAMIAMI HEIGHTS",
            "MANATEE POINT",
            "SOUTHEAST LEHIGH",
            "GULF SHORES ESTATES",
            "TERRY TICE + VANDERWALKER",
            "SANIBEL SHORES",
            "BUCKINGHAM AIR PARK",
            "LINCOLN PARK",
            "PINE GROVE TOWNHOUSES",
            "MANATEE BAY UNRECORDED SUBDIVISION",
            "ABACO POINTE",
            "BRAEBURN",
            "COURTSIDE LANDINGS",
            "SHIPPS LANDING",
            "GARDENS OF BONITA SPRINGS",
            "SMOKEHOUSE KEY",
            "GRANDE ISLE II",
            "WILDBLUE",
            "HACIENDA VILLAGE",
            "CARRARA",
            "HEATHERMOOR",
            "BURNT STORE ISLES",
            "COQUINA AT MAPLE RIDGE",
            "SUGARMILL",
            "REFLECTION KEY",
            "THE VISTAS",
            "SUNSET HOUSE",
            "CABANA CITY",
            "SCARECROW FARMS",
            "OMEGA AT BONITA BAY",
            "CORKSCREW ESTATES",
            "ANCONA",
            "GULF COVE TRAILER PARK CO-OP",
            "VILLA SOUTH",
            "ESTATES AT WYNDEMERE",
            "BURGUNDY FARMS",
            "IMPERIAL HARBOR",
            "FLORIDIAN FARMS",
            "CRAYTON PLACE",
            "WATSON W W",
            "THE DUNES SANIBEL ISLAND",
            "EVANSTON PARK CONDO",
            "ALTAMONT PARK",
            "QUAIL CREEK",
            "NAPLES MANOR",
            "SOUTHPORT ON THE BAY",
            "LIPARI",
            "LAKEWOOD PARK",
            "CALOOSA COVE",
            "HAMMOCK CREEK",
            "ANGLERS COVE",
            "GULF ISLAND MANOR",
            "PINE LAKES COUNTRY CLUB",
            "PINE VIEW VILLAS",
            "GLADES HAVEN RESORT AND MARINA",
            "TEE AND GREEN ESTATES",
            "DEER RUN FARMS",
            "TRADEWINDS APTS OF MARCO ISLAND",
            "MORNINGSIDE",
            "ROCK HARBOR",
            "Fort Myers Villas",
            "MERIDA",
            "RENAISSANCE VILLAGE",
            "SUNWARD CONDO",
            "CREEKSIDE CROSSING",
            "WILLIAMSBURG",
            "CRYSTAL LAKES",
            "MATLACHA ISLES",
            "SOUTHWINDS APTS OF MARCO ISLAND",
            "CAPE ROYAL",
            "REGENT",
            "MARCO VILLA",
            "PLAN OF RIVERSIDE",
            "SARACENO",
            "CASSIA",
            "VISTA POINTE",
            "RUBICON CONDO",
            "VIKING CONDO",
            "LAKE PLACID WATERWAY",
            "SUN-N-FUN MOBILE HOME VILLAGE",
            "BAYPORT VILLAGE",
            "CARLETON ESTATES",
            "SUNSET LAKE CONDO",
            "STRATFORD PLACE CONDO",
            "SEABURY",
            "FOUR MILE COVE",
            "TUSCANY",
            "VINTAGE BAY",
            "THE VILLAS AT VENEZIA",
            "TWIN LAKES",
            "Fort Denaud",
            "HANSONS W STANLEY SUBD",
            "LAUREL ESTATES",
            "MERION VILLAGE",
            "TRAILSIDE",
            "BROADVIEW VILLAS",
            "TUSCANY COVE",
            "KELLY PLAZA",
            "WOODLAKE AT BONITA BAY",
            "PRINCESS DEL MAR",
            "MORNINGSTAR",
            "MONTEROSSO",
            "COUNTRY CLUB",
            "DROP ANCHOR MOBILE HOME",
            "PALOMA",
            "Gullwing Beach Resort",
            "VENEZIA",
            "RIVER TERRACE CONDO",
            "SOMERSET",
            "WESTMINSTER",
            "BURNT STORE COLONY",
            "CHARLESTON PARK",
            "LABELLE TERRACE",
            "ROSEMARY PARK",
            "PRESERVE III",
            "BRIGHTON AT BAY COLONY",
            "MARINER POINTE CONDO",
            "ISLAND MANOR APTS",
            "ROYAL SEAFARER",
            "WINDWARD ISLE",
            "EVANS ADDITION",
            "ISLES OF PORTO VISTA",
            "EUROPEAN TOWNHOUSE",
            "COSTA DEL SOL",
            "COLONIES",
            "VERCELLI",
            "BOCA CIEGA MANOR",
            "TUSCANY ISLE",
            "BAREFOOT BAY",
            "TERRACE III AT RIVERWALK",
            "RIVIERA CLUB",
            "HEITMANS",
            "BELIZE",
            "PERIWINKLE PINES",
            "CAPTAINS BAY SOUTH",
            "ESTERO BAY SHORES",
            "VENETIAN POINTE",
            "PROMENADE EAST",
            "SAPPHIRE COVE",
            "MANATEE COVE",
            "PEPPER TREE",
            "SURF SONG CONDO",
            "FUNCKS SUBD",
            "SOUTH POINTE SOUTH",
            "GULLWING BEACH RESORT",
            "POINCIANA VILLAGE",
            "REMINGTON OAKS",
            "MONTURA RANCH SEC 34",
            "LA PENINSULA",
            "FLAGHOLE",
            "TRADEWINDS",
            "GULF EAST",
            "ESPERANZA",
            "BLACK BEAR RIDGE",
            "VICTORIA COVE CONDO",
            "DAVIS WOODS CONDOMINIUM",
            "TRAWLER VILLAGE",
            "IMMOKALEE HIGHLANDS",
            "FOXMOOR",
            "DUCHESS I CONDO",
            "PINE ISLAND VILLAS",
            "ESTERO PARK",
            "HAMPTON LAKES",
            "LAZY DAYS MOBILE VILLAGE",
            "RIVERS CONDO",
            "MILL RUN",
            "SUNSET",
            "BRENTWOOD",
            "TALL PINES",
            "GRIFFIN ESTATES",
            "GLENWOOD PARK",
            "MARIPOSA",
            "CYPRESS LANDING",
            "ST. TROPEZ",
            "RIVERWOODS PLANTATION",
            "NORTHWOOD",
            "GULF HARBOR",
            "PIRATES COVE",
            "EMERALD WOODS",
            "CATALINA ISLES",
            "STONEBRIDGE",
            "COCONUT RIVER",
            "CALUSA RIDGE",
            "HILLS T.P.",
            "EVERHIGHT ACRES",
            "LE DAUPHIN",
            "LUCARNO",
            "BROOKSHIRE VILLAGE",
            "SHALLOWS",
            "AQUA SHORES",
            "PELICAN LAKE RV RESORT",
            "MARCELLO",
            "BLIND PASS CONDO",
            "GULF SHORES",
            "LEAWOOD LAKES",
            "HOLIDAY MANOR",
            "HOLIDAY PARK",
            "BERMUDA BAY",
            "BLUE HERON",
            "MCGREGOR VISTA",
            "BIMINI ISLE",
            "BRITANNIA II",
            "SAWGRASS POINT",
            "TRIANA",
            "HARBOURSIDE",
            "VERANDA",
            "ROYAL GREENS",
            "SAVANNAH LAKES",
            "HICKORY SHORES",
            "AMADOR",
            "ONE",
            "FOREST LAKE TOWNHOMES",
            "SOUTH BAY PLANTATION",
            "HARLEM",
            "RAFFIA PRESERVE",
            "CYPRESS WALK",
            "SUNDIAL OF SANIBEL",
            "FRANKS",
            "LES CHATEAUX",
            "BAY HAVEN",
            "PINE ISLAND COVE",
            "ORCHID HARBOUR VILLAS CONDO",
            "LAUSANNE",
            "TERRA PALMA",
            "CAMDEN SQUARE",
            "BAY CEDAR",
            "KEEL CLUB",
            "STERLING LAKES II",
            "COLONNADE AT FORUM",
            "EVEREST CONDO",
            "TERRACE IV",
            "MANOR",
            "ROYAL POINTE",
            "CAPE GARDENS CONDO",
            "LAKE ARROWHEAD MOB VILLAGE",
            "CYPRESS PRESERVE",
            "ABBEY AT BERKSHIRE VILLAGE",
            "MARINA MANOR",
            "JASMINE BAY SOUTH"
        ].sort(),
        PropertySubType: [],
                
        PropertySubTypeOptions: [
            {id: 'Single Family Residence', value: 'Single Family'},
            {id: 'Low Rise (1-3)', value: 'Low Rise (1-3)'},
            {id: 'Mid Rise (4-7)', value: 'Mid Rise (4-7)'},
            {id: 'High Rise (8+)', value: 'High Rise (8+)'},
            {id: 'Apartment', value: 'Apartment'},
            {id: '2 Story', value: '2 Story'},
            {id: 'Townhouse', value: 'Town House'},
            {id: 'Multi Family', value: 'Multi Family'},
            {id: 'Duplex', value: 'Duplex'},
            {id: 'tx', value: 'Triplex'},
            {id: 'qx', value: 'Quadraplex'},
            {id: 'Manufactured Home', value: 'Manufactured'}
        ],
        CommunityFeatures: [],
        CommunityFeaturesExclude: [],
        CommunityFeaturesOptions: [
            {id: 'Gated', value: 'Gated'},
            {id: 'Non-Gated', value: 'Non-Gated'},
            {id: 'Golf', value: 'Golf'},
            {id: 'Golf Bundled', value: 'Golf Bundled'},
            {id: 'Golf Course', value: 'Golf Course'},
            {id: 'Golf Equity', value: 'Golf Equity'},
            {id: 'Golf Non Equity', value: 'Golf Non Equity'},
            {id: 'Golf Public', value: 'Golf Public'},
            {id: 'Clubhouse', value: 'Clubhouse'},
            {id: 'Dog Park', value: 'Dog Park'},
            {id: 'Fishing', value: 'Fishing'},
            {id: 'Fitness Center', value: 'Fitness Center'},
            {id: 'Lakefront Beach', value: 'Lakefront Beach'},
            {id: 'Park', value: 'Park'},
            {id: 'Pool', value: 'Pool'},
            {id: 'Tennis Court(s)', value: 'Tennis Court(s)'}
        ],
        AttachedGarageYN: 'Any',
        AttachedGarageYNOptions: [
            {id: 'Any', value: 'Any'},
            {id: 'Attached', value: 'Attached'},
            {id: 'Detached', value: 'Detached'}
        ],
        GarageSpaces: 'Any',
        GarageSpacesOptions: [
            {id: 0, value: 'Any'},
            {id: 1, value: '1+'},
            {id: 2, value: '2+'},
            {id: 3, value: '3+'},
            {id: 4, value: '4+'},
            {id: 5, value: '5+'},
            {id: 6, value: '6+'}
        ],
        priceRange: {
            min: 0, max: 0
        },
        priceRangeOptions: [
            {id: 0, value: 'Any'},
            {id: 100000, value: '$100,000'},
            {id: 150000, value: '$150,000'},
            {id: 200000, value: '$200,000'},
            {id: 250000, value: '$250,000'},
            {id: 300000, value: '$300,000'},
            {id: 350000, value: '$350,000'},
            {id: 400000, value: '$400,000'},
            {id: 450000, value: '$450,000'},
            {id: 500000, value: '$500,000'},
            {id: 600000, value: '$600,000'},
            {id: 700000, value: '$700,000'},
            {id: 800000, value: '$800,000'},
            {id: 900000, value: '$900,000'},
            {id: 1000000, value: '$1,000,000'},
            {id: 1250000, value: '$1,250,000'},
            {id: 1500000, value: '$1,500,000'},
            {id: 1750000, value: '$1,750,000'},
            {id: 2000000, value: '$2,000,000'}
        ],
        monthlyPayment: {
            min: 0, max: 0
        },
        monthlyPaymentOptions: [
            {id: 0, value: 'Any'},
            {id: 1000, value: 'less $1000'},
            {id: 1250, value: '$1,250'},
            {id: 1500, value: '$1,500'},
            {id: 1750, value: '$1,750'},
            {id: 2000, value: '$2,000'},
            {id: 2500, value: '$2,500'},
            {id: 3000, value: '$3,000'},
            {id: 3500, value: '$3,500'}
        ],
        beds: {
            min: 0, max: 5
        },
        baths: {
            min: 0, max: 5
        },
        recurringFee: {
            min: 0, max: 0
        },
        sqft: {
            min: 0, max: 0
        },
        yearBuilt: {
            min: 0, max: 0
        },
        WaterfrontFeatures: [],
        WaterfrontFeaturesOptions: [
            {id: 'Basin', value: 'Basin'},
            {id: 'Bay', value: 'Bay'},
            {id: 'Canal Front', value: 'Canal Front'},
            {id: 'Creek', value: 'Creek'},
            {id: 'Fresh Water', value: 'Fresh Water'},
            {id: 'Gulf Frontage', value: 'Gulf Frontage'},
            {id: 'Intersecting Canal', value: 'Intersecting Canal'},
            {id: 'Lagoon', value: 'Lagoon'},
            {id: 'Lake', value: 'Lake'},
            {id: 'Mangrove', value: 'Mangrove'},
            {id: 'Navigable', value: 'Navigable'},
            {id: 'No Gulf Access', value: 'No Gulf Access'},
            {id: 'On the Gulf Beach', value: 'On the Gulf Beach'},
            {id: 'Rip Rap', value: 'Rip Rap'},
            {id: 'River Front', value: 'River Front'},
            {id: 'Salt Water', value: 'Salt Water'},
            {id: 'Seawall', value: 'Seawall'},
            {id: 'None', value: 'None'},
        ],
        NABOR_PetsLimitMaxNumber: '',
        NABOR_PetsLimitMaxNumberOptions: [
            {id: 'Allowed', value: 'Allowed'},
            {id: 'Not Allowed', value: 'Not Allowed'}
        ],
        golfAccess: false,
        waterFrontView: false,
        guestHouse: false,
        newConstruction: false,
        dropDownAPI: 'https://nosnownaples.com/api/property/dropdown/res/City/'
    },
    reducers: {
        setPreviousPages: (state, action)=>{
            return{
                ...state,
                previousPages:[...state.previousPages, action.payload]
            }
        },
        resetPreviousPages: (state, action)=>{
            return {
                ...state,
                previousPages: [{page: 0, index: 0, start:0}]
            }
        },
        setPage: (state, action) =>{
            return{
                ...state,
                page:action.payload
            }
        },
        setLimit: (state, action) =>{
            return{
                ...state,
                limit:action.payload
            }
        },
        setKeyword: (state, action) => {
            return{
                ...state,
                keyword:action.payload
            }
        },
        setCity: (state, action) => {
            return{
                ...state,
                city:action.payload
            }
            
        },
        setCommunity: (state, action) => {
            return{
                ...state,
                community:action.payload
            }
            
        },
        setSubCondo: (state, action) => {
            return{
                ...state,
                subCondo:action.payload
            }
            
        },
        setPropertySubType: (state, action) => {
            return{
                ...state,
                PropertySubType:action.payload
            }
            
        },
        setCommunityFeatures: (state, action) => {
            // if(action.payload==='Non-Gated'){
            //     return{
            //         ...state,
            //         CommunityFeaturesExclude:action.payload
            //     }  
            // }
            return{
                ...state,
                CommunityFeatures:action.payload
            }
            
        },
        setAttachedGarageYN: (state, action) => {
            
            return{
                ...state,
                AttachedGarageYN:action.payload
            }
            
        },
        setGarageSpaces: (state, action) => {

            return{
                ...state,
                GarageSpaces:action.payload
            }
            
        },
        setPriceRange: (state, action) => {
            
            return{
                ...state,
                priceRange:{
                    ...state.priceRange,
                    [action.payload.key]: action.payload.value
                }
            }
            
        },
        setMonthlyPayment: (state, action) => {

            return{
                ...state,
                monthlyPayment:{
                    ...state.monthlyPayment,
                    [action.payload.key]: action.payload.value
                }
            }
            
        },
        setBeds: (state, action) => {
            var params = {
                min: action.payload[0],
                max: action.payload[1]
            }
            return{
                ...state,
                beds:params
            }
            
        },
        setBaths: (state, action) => {
            var params = {
                min: action.payload[0],
                max: action.payload[1]
            }
            return{
                ...state,
                baths:params
            } 
        },
        setRecurringFee: (state, action) => {
            return{
                ...state,
                recurringFee:{
                    min: action.payload.min,
                    max: action.payload.max
                }
            }
            
        },
        setSqft: (state, action) => {
            return{
                ...state,
                sqft:{
                    min: action.payload.min,
                    max: action.payload.max
                }
            }
            
        },
        setYearBuilt: (state, action) => {
            return{
                ...state,
                yearBuilt:{
                    min: action.payload.min,
                    max: action.payload.max
                }
            }
            
        },
        setWaterfrontFeatures: (state, action) => {
            return{
                ...state,
                WaterfrontFeatures:action.payload
            }
            
        },        
        setNABOR_PetsLimitMaxNumber: (state, action) => {
            return{
                ...state,
                NABOR_PetsLimitMaxNumber:action.payload
            }
            
        },        
        setGolfAccess: (state, action) => {
            return{
                ...state,
                golfAccess:action.payload
            }
            
        },        
        setWaterFrontView: (state, action) => {
            return{
                ...state,
                waterFrontView:action.payload
            }
            
        },       
        setGuestHouse: (state, action) => {
            return{
                ...state,
                guestHouse:action.payload
            }
            
        },        
        setNewConstruction: (state, action) => {
            return{
                ...state,
                newConstruction:action.payload
            }
            
        },

    },
    extraReducers: (builder) => {
        builder.addCase(fetchCity.fulfilled, addCityOptions);
        //builder.addCase(updateStop.fulfilled, updateItemsFromDB);
    },
})

export const { 
    setLimit,
    setPage,
    setPreviousPages,
    resetPreviousPages,
    setKeyword,
    setCity,
    setCommunity,
    setSubCondo,
    setPropertySubType,
    setCommunityFeatures,
    setAttachedGarageYN,
    setGarageSpaces,
    setPriceRange,
    setMonthlyPayment,
    setBeds,
    setBaths,
    setRecurringFee,
    setSqft,
    setYearBuilt,
    setWaterfrontFeatures,
    setNABOR_PetsLimitMaxNumber,
    setGolfAccess,
    setWaterFrontView,
    setGuestHouse,
    setNewConstruction
 } = ResSearchFields.actions

export default ResSearchFields.reducer
