export const subDivisions = () =>{
    return [
        "VANDERBILT LAKES",
        "NEWCASTLE",
        "THE DUNES",
        "SANDALWOOD VILLAGE",
        "VALENCIA AT PELICAN BAY",
        "AQUALANE SHORES",
        "NAPLES PARK",
        "CAPE CORAL",
        "OLDE TOWNE CONDO",
        "CHATEAUMERE",
        "MAPLELEAF VILLAS",
        "LAKOYA",
        "SHORE WOODS",
        "NOT APPLICABLE",
        "AVELLINO",
        "MIRASOL AT COCONUT POINT",
        "MALLARDS LANDING",
        "EDGEWATERS GARDENS",
        "RIVER TOWERS",
        "BRIARWOOD",
        "THE PLACE AT CORKSCREW",
        "DAVIS LAKE CONDO",
        "THE PINES",
        "LAUREL OAKS AT PELICAN BAY",
        "SATURNIA LAKES",
        "CALABRIA",
        "SORRENTO VILLAS",
        "OLDE CYPRESS",
        "ST CROIX",
        "HUNTINGTON LAKES",
        "ROYAL ARMS EXTENSION",
        "NAVARRA PARK",
        "THE BARCELONA",
        "SOCE FLATS",
        "LAUREL MEADOW",
        "HERITAGE POINTE",
        "SWEETWATER BAY",
        "STONECREEK",
        "KALEA BAY TOWER 100",
        "BELLA VITA",
        "BABCOCK NATIONAL",
        "IBIS WOODS",
        "BURNT STORE MARINA",
        "MATLACHA",
        "CENTRAL PARK SOUTH CONDOS",
        "SERANO",
        "OLE",
        "LAKEVIEW AT CARLTON LAKES",
        "VANDERBILT SHORES",
        "SURFSIDE CLUB AT COQUINA SANDS",
        "BONITA NATIONAL GOLF AND COUNTRY CLUB",
        "OLDE NAPLES",
        "SEYCHELLES",
        "BILTMORE AT BAY COLONY",
        "CALOOSA ISLES II CONDO",
        "PRESTWICK PLACE",
        "LEHIGH ACRES",
        "PROVINCETOWN",
        "CASA BONITA II",
        "RAVENNA",
        "NAPLES HIDEAWAY CLUB",
        "VILLAGES AT COUNTRY CREEK",
        "PRIVATEER OF FT MYERS BEACH",
        "FAIRWAYS",
        "CHESAPEAKE MANOR",
        "HERITAGE LANDING GOLF AND COUNTRY CLUB",
        "DEL MAR",
        "EAGLE CREEK",
        "ST NICOLE",
        "ESPLANADE AT HACIENDA LAKES",
        "VILLA DANNA",
        "RIVERBEND MOTORCOACH RESORT",
        "MARCO ISLAND",
        "SEASONS AT NAPLES CAY",
        "DONAX VILLAGE CONDO",
        "BERMUDA COVE",
        "EVERGLADES TOWN",
        "GOLDEN GATE ESTATES",
        "KEY MARCO",
        "TURTLE POINT COVE",
        "REFLECTION LAKES",
        "ROYAL PALM GOLF ESTATES",
        "ST VINCENTS",
        "SEASONS AT BONITA",
        "SORRENTO",
        "BONITA FARMS",
        "PORT CHARLOTTE",
        "PORT LABELLE",
        "COPPER OAKS",
        "COMPASS POINT SOUTH",
        "PEBBLE CREEK",
        "VANDERBILT SURF COLONY",
        "PRINCETON PLACE",
        "VILLAGES AT EMERALD BAY",
        "ST MARISSA",
        "REGATTA",
        "EAGLEWOOD",
        "ESPLANADE CLUB",
        "GRANDE PHOENICIAN",
        "NEW SUBDIVISION",
        "TUSCANY GARDENS",
        "VILLAGE WALK OF BONITA SPRINGS",
        "SANDPIPER ISLE",
        "ADMIRALTY POINT",
        "ST SIMONE",
        "GULF BREEZE AT VANDERBILT",
        "NAPLES SANDPIPER BAY CLUB",
        "L'AMBIANCE",
        "CRESCENT",
        "PAVILION CLUB",
        "VIANSA",
        "SARATOGA COLONY",
        "PROVENCE",
        "JASPER",
        "EAGLE COVE",
        "ORCHARDS",
        "VANDERBILT VILLAS",
        "GREENLINKS",
        "TERRACE",
        "BARRINGTON CLUB",
        "NAPLES COVE",
        "FAIRWAYS AT EMERALD GREENS",
        "BRIDGEWATER BAY",
        "LUGANO",
        "ARIELLE",
        "BAY WOODS",
        "MARQUESA AT BAY COLONY",
        "CARAWAY LAKES",
        "BEACH WALK CONDO",
        "HOLLY GREENS VILLA",
        "CAY LAGOON",
        "LALIQUE",
        "PARK SHORE",
        "MARCO BEACH",
        "TIMBERCREEK",
        "BRITANNIA I",
        "MONTE CARLO CLUB",
        "CYPRESS GLEN",
        "FURSE LAKES",
        "VANDERBILT GULFSIDE",
        "ST TROPEZ",
        "MANSION HOUSE",
        "IMPERIAL GARDENS",
        "MONTENERO",
        "LAS BRISAS AT SPANISH WELLS",
        "WILLOWBROOK",
        "FORT DENAUD ACRES UNIT 2",
        "AZURE AT HACIENDA LAKES",
        "VILLAS OF PARK SHORE",
        "VERANDAS AT TIGER ISLAND",
        "COLONADE",
        "PAVIA",
        "ISLAND COVE OF CAPE CORAL",
        "ISLES OF COLLIER PRESERVE",
        "TURNBERRY",
        "ACREAGE HEADER",
        "KEEWAYDIN ISLAND",
        "RIVERWOOD",
        "REGENCY RESERVE",
        "INDIGO LAKES",
        "COUNTRY CLUB ESTATES",
        "FLAMINGO FAIRWAYS II",
        "BUTTONWOOD KEY",
        "BONITA SHORES",
        "LAGUNA ROYALE",
        "STELLA MARIS",
        "ARTESIA",
        "GLENEAGLES",
        "BONITA BEACH CLUB",
        "HIDEAWAY HARBOR",
        "HERITAGE BAY",
        "THE SEVILLE",
        "COQUINA SANDS",
        "SAIL HARBOUR",
        "GRANDE CAY",
        "RESERVE AT NAPLES",
        "VANDERBILT BEACHCOMBER",
        "SOLAMAR",
        "MIRASOL",
        "PUNTA GORDA",
        "COACH HOMES AT HERITAGE BAY",
        "LA MER",
        "LAUREL GREENS",
        "TRIESTE AT BAY COLONY",
        "ASCOT",
        "GRANDE DOMINICA",
        "BELLERIVE",
        "NORTH STAR YACHT CLUB",
        "SANIBEL VIEW CONDO",
        "FOREST LAKES GOLF AND TENNIS CLUB",
        "SOUTH GULF COVE",
        "TARPON VILLAGE APTS",
        "ROTONDA MEADOWS",
        "WHEELERS SUBD",
        "THE RESIDENCES AT COCONUT POINT",
        "ACREAGE",
        "FORT MYERS",
        "MARIANA PARK",
        "CHARLOTTE SHORES",
        "EL DORADO ACRES",
        "HIGHLAND ESTATES UNRECORDED SUBDIVISION",
        "CALOOSA HAMMOCK",
        "LAKEVILLE",
        "NORTH FORT MYERS",
        "SEABREEZE SOUTH",
        "FOXWOOD",
        "MCGREGOR ESTATES",
        "SUNCOAST ESTATES UNREC",
        "ESTATES",
        "LABELLE",
        "PINE ISLAND CENTER",
        "SHANNONS",
        "MOORE HAVEN",
        "SAN CARLOS PARK",
        "ALVA",
        "MILLERS PARK",
        "LABELLE ESTATES",
        "SUNSET CAY VILLAS",
        "BONITA SPRINGS",
        "BURNT STORE LAKES",
        "CORDERA",
        "MONTURA RANCH ESTATES",
        "SUNCOAST ESTATE",
        "NAPLES SQUARE",
        "TROPICAL GULF ACRES",
        "PALM BAY ESTATES",
        "RUSSELL PARK",
        "SONOMA",
        "WORLD TENNIS CENTER",
        "BEACH HOMES",
        "MARGARET ACRES",
        "COUNTRYSIDE CONDOS",
        "HUNTERS RIDGE",
        "CONTESSA AT BAY COLONY",
        "CYPRESS TRACE",
        "BEACHWALK VILLAS",
        "VERONA LAGO",
        "CITRUS SPRINGS",
        "NORTH PORT",
        "BURNT STORE MEADOWS",
        "KREAMERS AVOCADO SUBD",
        "GREENBRIAR",
        "LAKE MUREX",
        "DOVER PARC",
        "TIMBER TRAILS",
        "GULF COVE",
        "PINE ISLAND RIDGE",
        "BUCKINGHAM",
        "ROTONDA SANDS",
        "GRACIOUS HOMES SUBD",
        "NORTH CAPTIVA DUNES",
        "RIVERCREEK",
        "TOWN AND RIVER",
        "METES AND BOUNDS",
        "BAYVIEW ACRES",
        "REGENT PARK",
        "SUTTON CAY",
        "SANCTUARY AT WULFERT",
        "NORTH BELLE MEADE",
        "VANDERBILT TOWERS",
        "MYSTIC GREENS",
        "TUCKAWEYE",
        "PINE RIDGE",
        "RIALTO",
        "PINEWATER PLACE",
        "NORTH LABELLE GLADES",
        "STONEYBROOK",
        "FOUNTAIN LAKES",
        "LEILANI",
        "CAPE CORAL - LEE COUNTY INDUSTRIAL PARK",
        "CORAL HARBOR",
        "PLANTATION ISLAND",
        "CROWN POINTE SHORES",
        "MERIDIAN CLUB",
        "BAREFOOT BEACH CLUB",
        "PARK SHORE RESORT",
        "GULF ACRES",
        "COLONIAL COUNTRY CLUB",
        "BEARS PAW",
        "AVALON",
        "VANDERBILT LANDINGS",
        "BAREFOOT PELICAN",
        "SANDY LANE",
        "CONCORDIA",
        "PLAYERS COVE",
        "BUCKINGHAM PARK",
        "SOUTH SEAS CLUB CONDO",
        "BELLAMAR",
        "OAKWOOD VILLAS",
        "VISTAS AT PARK SHORE",
        "MOORINGS",
        "TIMARRON",
        "DELASOL",
        "SURFSEDGE",
        "CONNERS",
        "WIGGINS LAKES AND PRESERVES",
        "VILLAS ENCANTADA",
        "TROPHY CLUB",
        "CLARIDGE",
        "KNIGHTS BOKEELIA ISLE",
        "TRA VIGNE",
        "ELEVEN HUNDRED CLUB",
        "OAKWOOD",
        "EXECUTIVE CLUB",
        "GRANDE EXCELSIOR",
        "HIDEAWAY BEACH",
        "COLONIAL LINKS",
        "PARK SHORE TOWER",
        "ST MAARTEN",
        "SARATOGA",
        "YACHT HARBOR MANOR",
        "LEHIGH ESTATES",
        "CONCORD",
        "Vanderbilt Villas",
        "MARINER APTS MARCO ISLAND",
        "PALM COLONY",
        "SHERRILL POINT",
        "THE ENCLAVE AT NAPLES",
        "NAPLES CLUB ESTATES",
        "EAGLE CREEK VILLA HOMES",
        "KENSINGTON GARDENS",
        "GULF SOUTH",
        "BAYFRONT",
        "SEAWATCH",
        "BONITA BEACH",
        "WHISKEY CREEK",
        "MOODY RIVER ESTATES",
        "SIENA",
        "NEWPORT MANORS CONDO",
        "COACH HOUSE",
        "RIVERSIDE CLUB",
        "ESPLANADE",
        "BERMUDA POINTE",
        "FOUR SEASONS",
        "NAPLES CONTINENTAL",
        "SAVOY",
        "SEASCAPE",
        "GLENCOVE",
        "NAVONA AT THE COLONY",
        "FOREST LAKES",
        "BRIDGETOWN",
        "CALUSA BAY NORTH",
        "INDIAN WELLS GOLF VILLAS",
        "LAKESIDE CARRIAGE HOMES",
        "CHATEAU SUZANNE",
        "MEADOWLARK ESTATES",
        "HARBORSIDE TERRACE",
        "SOUTH POINTE WEST CONDO",
        "FORT MYERS SHORES",
        "MANATEE COVE CONDO",
        "TRIESTE",
        "CHERRY ESTATES",
        "HARBOURTOWNE CONDO",
        "MUSTANG ISLAND",
        "PALM BEACH LANDINGS",
        "PORT ROYAL",
        "ANA'S PLACE",
        "NAPLES BATH AND TENNIS CLUB",
        "BONITA ISLES",
        "WATERFORD AT WORTHINGTON",
        "GULF REFLECTIONS",
        "MAJORS",
        "TERRACE VI",
        "PELICAN RIDGE",
        "WEDGE WOOD AT THE STRAND",
        "RIVERSTONE",
        "CASTALINA",
        "CARRINGTON",
        "ASCOT AT LELY RESORT",
        "ST KITTS",
        "GULF VIEW BEACH CLUB",
        "NORTHSHORE LAKE VILLAS",
        "BRIDGEWATER",
        "MONACO BEACH CLUB",
        "ISLAND BREEZE",
        "BELLA FIRENZE",
        "STRATFORD PLACE",
        "PELICAN MARSH",
        "THE CARLYSLE",
        "ST JAMES CITY",
        "NAPLES IMP CO LITTLE FARMS",
        "ROTONDA LAKES",
        "SHELL HARBOR",
        "PALMETTO PINES COUNTRY CLUB",
        "INDIAN HILLS",
        "JOSE'S HIDEAWAY",
        "LEHIGH PROPERTIES",
        "MARION OAKS",
        "PUNTA GORDA ISLES",
        "HARBOR HEIGHTS",
        "CHARLOTTE RANCHETTES",
        "BANYAN VILLAGE",
        "RIVERBEND",
        "ISLAND OF HAPPINESS",
        "BURNT STORE VILLAGE",
        "SERATA",
        "BAYVIEW PARK",
        "SHOREHAVEN ESTATES",
        "OLD FORT DENAUD",
        "ADMIRAL LEHIGH ESTATES",
        "WEST LEHIGH",
        "KREAMERS AVOCADO UNREC",
        "SOUTHWOOD",
        "LEELAND HEIGHTS",
        "ALDEN ACRES UNRECORDED SUBDIVISION",
        "CASTAWAY KEY UNRECORDED SUBDIVISION",
        "RIDGEVIEW ESTATES",
        "ROTONDA VILLAS",
        "PAGE PARK",
        "MIRROR LAKES",
        "LEISURE ACRES",
        "FRANK C ADAMS SUBDIVISION UNRECORDED SUBDIVISION",
        "JONATHAN HARBOUR",
        "PIONEER PLANTATION SEC 35",
        "NORTH LABELLE",
        "MONTURA RANCH SEC 14",
        "USEPPA ISLAND",
        "PINE ISLAND",
        "SUNDIET VILLAGE",
        "WILDCAT FARMS",
        "CALOOSA ESTATES UNIT 3",
        "GULF HAVEN",
        "CAPE ROMANO",
        "CHANTECLAIR MAISONETTES",
        "PINEHURST",
        "ALTA MAR",
        "PIONEER PLANTATION",
        "BEACHVIEW COUNTRY CLUB ESTATES",
        "PIONEER PLANTATION SEC 22",
        "CASA BONITA ROYALE",
        "SANIBEL HARBOURS",
        "KREAMERS SUBD",
        "WHOLESALE PARK",
        "SOUTH PUNTA GORDA HEIGHTS",
        "CLEWISTON",
        "MONTURA",
        "900 BUILDING",
        "CAPTAINS COVE",
        "PINE ISLAND SHORES UNIT 5",
        "COPELAND VILLAGE",
        "GERBER GROVES SEC 2",
        "DEVONWOOD",
        "MONTEVERDI",
        "PIRATE HARBOR",
        "HERONS GLEN",
        "HICKEY CREEKSIDE",
        "LAMORADA",
        "VENETIAN BAYVIEW",
        "WEST BAY CLUB",
        "BAY POINTE YACHT & RACQUET CLUB",
        "DI NAPOLI",
        "HUNTINGTON LAKES II",
        "LAKE FAIRWAYS COUNTY CLUB",
        "MIRAVISTA",
        "TERRACES AT PARK SHORE",
        "BERKSHIRE LAKES",
        "WORTHINGTON WAY",
        "DORCHESTER",
        "CHIASSO",
        "CAPE HARBOUR",
        "COCONUT BAY",
        "INTERLACHEN",
        "GARDEN LAKES",
        "ANDALUCIA",
        "ALEXANDRA",
        "GRAND CYPRESS I",
        "LAKESIDE GARDENS",
        "VANDERBILT YACHT RACQUET",
        "VALENCIA BONITA",
        "OAKES ESTATES",
        "DIAMOND",
        "AVON PARK",
        "FLORENCIA",
        "VERONA WALK",
        "DEAUVILLE LAKE CLUB",
        "SONSETTE",
        "VILLAS",
        "TANGLEWOOD",
        "OAKMONT",
        "SAN REMO",
        "CARRIAGE HOMES AT LIVINGSTON LAKES",
        "BOLERO AT TIBURON",
        "BREAKWATER",
        "TERRABELLA",
        "MARENGO",
        "BERMUDA CAYS",
        "TURTLE LAKE GOLF COLONY",
        "HYDE PARK",
        "BEAUMER",
        "ADDISON RESERVE",
        "BELLAVISTA",
        "WINDING STREAM",
        "COLONIAL SHORES",
        "MASTERS RESERVE",
        "PASEO",
        "TREVI",
        "LONGSHORE LAKE",
        "LAKESIDE",
        "TAMIAMI VILLAGE",
        "SHERWOOD",
        "DEL VERA COUNTRY CLUB",
        "MATERA",
        "BERMUDA CLUB CONDO",
        "COTTAGE POINT UNREC",
        "MARQUESA ISLES OF NAPLES",
        "HIDDEN LAKES AT WOODS EDGE",
        "DEER CROSSING",
        "HAMILTON PLACE",
        "FOREST VILLAGE",
        "GIAVENO",
        "LITTLE HICKORY SHORES",
        "EL SOL",
        "ISLANDS END",
        "LAKE TIMBER",
        "SANCTUARY",
        "RIVERS REACH",
        "BRITANNIA IV",
        "VILLAGES AT EMERALD LAKES",
        "OASIS",
        "NAPLES BAY RESORT",
        "OXFORD VILLAGE",
        "ELEVEN ELEVEN CENTRAL",
        "GATOR CIRCLE",
        "CASCADA",
        "SAVONA",
        "CASORIA",
        "OLD MARCO VILLAGE",
        "SAFETY HARBOR CLUB",
        "SAN CARLOS PARK GOLF COURSE ADDITION",
        "RIVER FOREST",
        "PALMONA PARK",
        "COMPASS LANDING",
        "MONTURA RANCH SEC 24",
        "ARBORWOOD PRESERVE",
        "ST ANDREWS VERANDAS",
        "BARLETTA",
        "SWEET BAY AT SHADOW WOOD",
        "HALLENDALE",
        "THE HAMPTONS",
        "COTTESMORE",
        "CARLYSLE AT BAY COLONY",
        "WEDGEWOOD",
        "ROYAL HARBOR",
        "MILLBROOK",
        "CASA BONITA I",
        "MARBELLA ISLES",
        "MASTIQUE",
        "PEBBLE SHORES",
        "OPAL",
        "PALERMO",
        "WHISPER TRACE",
        "PARTRIDGE POINTE",
        "ALBERI ACQUA",
        "ST LAURENT",
        "GREENGATE",
        "JASMINE BAY NORTH",
        "RIVERWALK COVE",
        "RICHARDSONS O L SUBD",
        "HAWK'S NEST",
        "BEACH BREEZE",
        "ESTUARY AT GREY OAKS",
        "BEACHWALK GARDENS",
        "GOLDEN GATE CITY",
        "DEEP CREEK",
        "GRAND PINES",
        "BEACHWALK HOMES",
        "SUNNY GROVE",
        "TRIPLE R ACRES",
        "WINDING CYPRESS",
        "CHARDONNAY",
        "PIERRE CLUB",
        "EGRETS WALK",
        "BAYSHORES",
        "MUSTANG VILLAS",
        "SEASCAPE CONDO",
        "HALFMOON POINT",
        "PORT AU VILLA",
        "BURNING TREE",
        "RIDGE LAKE",
        "LOGAN WOODS",
        "BARBADOS",
        "ROSEWOOD",
        "GOLDEN SHORES",
        "LA SCALA AT VANDERBILT BEACH",
        "PONZIANE",
        "CAYMAN",
        "VIA VENETO",
        "CASA BONITA GRANDE",
        "AMBER",
        "SEA CHASE",
        "COCONUT SHORES",
        "CALOOSA PRESERVE",
        "IMMOKALEE ANCHORAGE",
        "ADMIRALS WALK",
        "LINDSFORD",
        "VANDERBILT BAY",
        "DIXON PARK",
        "ONYX TOWNHOME VILLAS",
        "VANDERBILT BEACH AND HARBOUR",
        "PALMETTO POINT",
        "MCGREGOR ISLES",
        "LA PERLE",
        "PARQUE DE LEON",
        "400 LA PENINSULA",
        "WEBER WOODS",
        "ANTILLES",
        "MARINA BAY",
        "PELICAN BAY WOODS",
        "NAPLES BETTER HOMES",
        "MANGROVE BAY",
        "COTTAGE COLONY WEST CONDO",
        "MCGREGOR GARDENS",
        "VILLA PINES",
        "GULFCOAST INN OF NAPLES",
        "SILVER LAKES",
        "EAST ENGLEWOOD",
        "LONG MEADOW",
        "BRIARCLIFF",
        "NORTH RIVER ESTATES",
        "GRANDE ISLE III",
        "HARBOR TOWERS",
        "NEW WATERFORD",
        "HIDDEN LAKES",
        "PIPERS POINTE",
        "IBIS COVE",
        "HAWKSRIDGE",
        "SPINEL",
        "NEAPOLITAN CLUB",
        "GLADES COUNTRY CLUB",
        "IBIS CLUB INTERNATIONAL",
        "COACH HOMES",
        "FOREST PARK",
        "THE SHORES",
        "RUBY AT SUNSTONE",
        "ISLAND HARBORS",
        "PINE ISLAND ESTATES",
        "SONOMA LAKE",
        "BOTANICA LAKES",
        "LOVERS KEY BEACH CLUB",
        "Cape Coral",
        "EAST BAYSHORE",
        "OYSTER BAY",
        "IMPERIAL GOLF ESTATES",
        "BIG CYPRESS GOLF COUNTRY CLUB",
        "MAGNOLIA LANDING",
        "GENOVA",
        "LEXINGTON COUNTRY CLUB",
        "COCONUT CREEK",
        "BAY COLONY SHORES",
        "BAY VILLAS",
        "BERMUDA LINKS",
        "BARRINGTON AT PELICAN BAY",
        "LAKEWOOD",
        "ISLAND ACRES",
        "BONAIR",
        "BRISTOL PARC",
        "DEEP LAGOON ESTATES",
        "GREYHAWK AT GOLF CLUB OF THE EVERGLADES",
        "TOWER POINTE AT ARBOR TRACE",
        "BELLA TERRA",
        "FLORIDA HENDRY LAND TRACTS",
        "COASTAL ESTATES",
        "HIGH POINT PLACE",
        "IONA GARDENS",
        "IMPERIAL WILDERNESS",
        "VILLAS AT PELICAN BAY",
        "SPRING CREEK VILLAGE",
        "CANOPY",
        "APOLLO",
        "OAK STREET UNREC",
        "HIGH POINT COUNTRY CLUB",
        "PALAZZO",
        "EMERSON PARK",
        "HARBORAGE",
        "CRAIGS SUBDIVISION",
        "SILVERWOOD",
        "CAMILLE GARDENS",
        "LAKEWOOD VILLAS",
        "ADMIRAL'S ISLE",
        "FISHERMANS WHARF CONDO",
        "BAYSHORE ESTATES SUBDIVISION",
        "PALMETTO PALMS R V",
        "BIMINI BAY",
        "STERLING GREENS",
        "ESPLANADE BY THE ISLANDS",
        "HEATHERSTONE",
        "ANTIGUA",
        "CANDLEWOOD LAKE ESTATES",
        "NUTMEG VILLAGE",
        "HOLLY TERRACE",
        "COMMODORE CLUB",
        "LANDING",
        "LUCAYA CAY",
        "FAIRWAYS AT PAR TWO",
        "TIDEWATER ISLAND",
        "VISTA WILDBLUE",
        "BANYAN WOODS",
        "POINSETTIA PARK MOBILE HOME CO-OP INC",
        "SERENDIPITY",
        "CERCINA",
        "GULFVIEW APTS OF MARCO ISLAND",
        "TWO BY TWO",
        "THE EGRET",
        "SEA ISLES",
        "THE COVE",
        "JASMINE POINTE",
        "MARINERS COVE",
        "PARADISE VILLAGE AT MARCO BEACH",
        "MONTURA RANCH SEC 27",
        "YACHT CLUB COLONY",
        "DORADO AT FIDDLER'S CREEK",
        "JACARANDA",
        "DEL WEBB",
        "YACHT CLUB",
        "SEAGLASS AT BONITA BAY",
        "FORT MYERS BEACH CAMPGROUND",
        "SEVEN LAKES",
        "AUDUBON COUNTRY CLUB",
        "TWIN EAGLES",
        "DOLPHIN WAY",
        "CAPE COLONY CONDO",
        "SOMERVILLE",
        "FOREST HILLS",
        "SCHOONER BAY COLUMBIA",
        "ASHTON PLACE",
        "KINLEYLAND",
        "COOPERS PARK",
        "CALDECOTT",
        "CASCADES",
        "CAPTIVA PALMA UNRECORDED SUBDIVISION",
        "PAR ONE",
        "GRAND OLE MAN",
        "PARADISE SHORES",
        "HIDDEN LAKE VILLAS",
        "ST. CHARLES HARBOUR",
        "SAN MATEO",
        "SANIBEL SURFSIDE CONDO",
        "ENTRADA",
        "BANYAN BAY",
        "GRANDVIEW",
        "ISLAND WALK",
        "ARROWHEAD RESERVE",
        "EAGLE CAY",
        "LEISURE TIME CAMPSITES",
        "MARTINIQUE",
        "LAKEMONT COVE",
        "CASTELLA",
        "POINTE AT PELICAN LANDING",
        "CAVENDISH COURT",
        "TURNER OAK HILL ESTATES",
        "REFLECTION LAKES COMMERCIAL CENTER",
        "THE STRADA",
        "HARBORSIDE WEST",
        "ST RAPHAEL",
        "VILLAS AT QUAIL RUN",
        "BONITA FAIRWAYS",
        "SOUTH SEAS",
        "TROPIC TERRACE",
        "CORKSCREW SHORES",
        "WESTBROOK",
        "ARROYAL HEIGHTS",
        "SOUTH BEACH CLUB",
        "LAGUNA",
        "TOWN MANOR",
        "MIRAMAR",
        "PALM RIVER ESTATES",
        "ARBORS AT PELICAN MARSH",
        "MOON LAKE",
        "ARBOR LAKES CONDO",
        "BELLINI",
        "SANDOVAL",
        "BONITA BEACH PLANTATION HOUSE",
        "FLAMINGO VILLAGE HOMES",
        "ALABAMA GROVE TERRACE",
        "VILLAGE WALK",
        "LEESURE VILLAGE",
        "Cinnamon Cove",
        "CROSS CREEK COUNTRY CLUB",
        "Terrace",
        "KELLY GREENS",
        "HARBOUR ISLE YACHT AND RACQUET CLUB CONDO",
        "GARDENS AT BERMUDA LINKS",
        "AMBLEWIND",
        "PALMETTO COVE",
        "SAN CARLOS ESTATES",
        "PROMENADE",
        "GREENWOOD VILLAGE AT BRECKENRIDGE",
        "LELY ISLAND ESTATES",
        "Runaway Bay",
        "BANYAN CLUB",
        "LAKE PARK",
        "SALERNO AT BAY COLONY",
        "NAPLES HEIGHTS",
        "ALLEGRO",
        "LE CIEL VENETIAN TOWER",
        "MEADOWBROOK ESTATE",
        "WINTERPARK",
        "ISLES OF CAPRI",
        "PINE RIDGE OF FORT MYERS VILLAGE",
        "VANDERBILT PLACE",
        "TEN MILE ANCHORAGE",
        "RIVER TOWERS CONDO",
        "ORANGE BLOSSOM RANCH",
        "ENCLAVE",
        "EAST STADLER FARMS",
        "KINGWOOD GARDEN",
        "WHISKEY POINTE",
        "ROOKERY POINTE",
        "LITTLE HICKORY BAY",
        "GRAMAC",
        "WILLOUGHBY ACRES",
        "WESTWOOD ACRES",
        "HIGHLAND PARK EAST",
        "GOLDEN ACRES",
        "CYPRESS WOODS ESTATES",
        "GULFSIDE",
        "LIVINGSTON WOODS",
        "TAMARIND CAY",
        "GULF HEIGHTS",
        "VILLA VIZCAYA",
        "DANFORTH LAKES",
        "CRANBROOK HARBOR",
        "SOUTHPOINTE YACHT CLUB",
        "GORES A M SUBD",
        "LELY PINES",
        "DEERWOOD",
        "BURTWOOD",
        "WHEELERS H L SUBD",
        "HENDERSON CREEK PARK",
        "CORONADO",
        "ISOLA BELLA",
        "THE NATIONAL GOLF & COUNTRY CLUB AT AVE MARIA",
        "FAIRMONT",
        "ATRIUM CONDO",
        "ST JUDE HARBORS",
        "BUTTONWOOD HARBOR",
        "COLONIAL ACRES UNIT 2",
        "VIZCAYA VILLAS UNREC",
        "BEACH AND TENNIS CLUB",
        "FLAMINGO FAIRWAYS",
        "LEHIGH PARK",
        "TARPON LANDINGS",
        "THE COVE AT SIX MILE",
        "BONITA PINES",
        "MAPLE GARDENS",
        "MAPLE RIDGE",
        "SOUTHWEST LEHIGH",
        "FLORIMOND MANOR",
        "ESTERO SPRINGS",
        "SUBURBAN PARK",
        "BELLERA WALK",
        "BAYSHORE HEIGHTS",
        "RIDGEWOOD PARK",
        "STORTER",
        "WILDCAT COVE",
        "HOLEUSA ESTATES",
        "PARKSIDE",
        "GOLDEN GATE PROF BLDG",
        "HAMPTON PARK",
        "BEACHMOOR",
        "555 ON FIFTH",
        "LARGO",
        "TIMBER CREEK",
        "SAGAMORE COURT",
        "HARBOUR LANDINGS",
        "WINDSOR MANOR CONDO",
        "BEACH ESTATES",
        "CAPE PARKWAY",
        "OAKMONT VILLAGE",
        "CARVER PARK",
        "WATERWAY ESTATES",
        "DELAY PARK",
        "WATERSIDE AT BAY BEACH",
        "OKEECHOBEE",
        "RIVER BY",
        "RIVER HARBOR CLUB CONDO",
        "CORAL BAYVIEW CONDO",
        "CITY VILLAGE",
        "PALACO GRANDE",
        "DONOGHUES 2ND SUBD",
        "LABELLE RANCHETTES",
        "MYSTIQUE",
        "CARISSA CONDO",
        "ADMIRALTY YACHT & RACQUET CLUB",
        "BROOKSIDE",
        "PARKWOODS TOWNHOUSE COMMUNITY",
        "HOMESTEAD PARK",
        "HARBOUR LIGHTS",
        "RESERVE II",
        "PRIMA LUCE",
        "WINDSOR ACRES",
        "OAKS",
        "RIVER REACH",
        "ROBERT DODDS SUBD",
        "COPPER COVE PRESERVE",
        "SUNNY PALM ESTATES",
        "SEPTEMBER ESTATES AMENDED",
        "ANCHORAGE AT VANDERBILT",
        "PIPERS GROVE",
        "LAKEVIEW TERR",
        "CAMELOT PARK",
        "MUSE",
        "VILLAGES OF STELLA MARIS",
        "CORKSCREW WOODLANDS",
        "WEDGMONT",
        "TOWNHOMES OF SAN SIMEON",
        "SPELLBINDER VILLAS",
        "FEATHER SOUND",
        "GORTONS",
        "CORAL FALLS RESORT",
        "VILLAGES",
        "AVELLINO ISLES",
        "LIGHTHOUSE BAY",
        "LEE COUNTY INDUSTRIAL PARK",
        "YORK MANOR",
        "BERMUDA ISLES",
        "KALEA BAY TOWER 200",
        "MAHOGANY BEND",
        "CLERMONT",
        "CYPRESS LAKES MANOR SOUTH",
        "TERRACE V",
        "BABCOCK",
        "ADMIRALTY HOUSE",
        "SMOKEHOUSE HARBOUR",
        "GULF MANOR CONDO",
        "ERIN LAKE",
        "CLEAVES CORNER UNREC PLAT",
        "ESSEX HOUSE",
        "ROYAL WOOD",
        "EGRET LANDING",
        "ROYAL PALM CLUB",
        "HORSE CREEK ESTATES",
        "FRANCISCAN GARDENS",
        "PEBBLE POINTE",
        "SAWGRASS",
        "PINE MANOR",
        "BUENA VISTA",
        "WHISPERING PINES",
        "CORALEE CONDO",
        "ROBERTS C F SUBD",
        "ORANGE BLOSSOM ESTATES",
        "GERBER GROVES SEC 1",
        "MATERITA",
        "WILLIAMS PARK ADD",
        "VILLA MAR BONITA BEACH",
        "TWIN LAKE ESTATES",
        "MIRADA AT ESTUARY",
        "VENETO",
        "PORTICO",
        "SANDALFOOT CONDOMINIUM",
        "AMERICA OUTDOORS CONDO ASSOCIATION INC",
        "LA GALLERIA",
        "WINDJAMMER VILLAGE AT THE LAND",
        "TWIN PALMS",
        "QUAIL WEST",
        "BRIGHTWATER",
        "ENBROOK",
        "COURTYARDS OF CAPE CORAL SOUTH",
        "EAGLE RIDGE",
        "COUNTRY CLUB MANOR",
        "LAKEWOOD VILLAGE",
        "WINDSOR PLACE",
        "BERMUDA DUNES CONDO",
        "KINGS PORT",
        "RIVERWIND COVE",
        "PEBBLEBROOKE LAKES",
        "RIDGEWOOD OF NAPLES",
        "MARK I",
        "CALOOSA VIEW",
        "POSITANO PLACE",
        "GULFHAVEN",
        "TIMBER RIDGE",
        "CORAL OAKS GOLF COURSE",
        "MCGREGOR VILLAGE CONDO",
        "LAKE KELLY",
        "COLLIER & RUPERT",
        "BEVERLY HILLS",
        "NAPLES CASAMORE",
        "HENDRY CREEK",
        "PALM ACRES",
        "LAUREL OAKS",
        "BELLA VIDA",
        "ISLAND SHORES",
        "JEFFCOTTS WM ADD RESUB",
        "CENTRAL GARDEN",
        "PINE ISLAND TROPICAL HOMESITES",
        "RIVERSIDE AVENUE VILLAS",
        "COLONIAL POINTE",
        "VANDERBILT PALMS",
        "ESTERO COVE CONDO",
        "ARBEL",
        "SPLINTERWOOD",
        "GLENVIEW",
        "HIGHLAND PINES ESTATES",
        "PINE HURST ESTATES",
        "GROVE HEIGHTS",
        "MAGNOLIA ISLES",
        "WILLOW RIDGE",
        "OAK KNOLL AT BONITA BAY",
        "PALMAS DEL SOL",
        "NAPLES TWIN LAKES",
        "SOUTHWINDS APTS OF NAPLES",
        "MARBLEBROOK",
        "SIX LAKES COUNTRY CLUB",
        "LAKE CAMILLE CONDO",
        "CYPRESS CAY",
        "INDIGO PRESERVE",
        "TWIN BROOKS ESTATES",
        "GUILFORD ACRES",
        "AVIANO",
        "CYPRESS LAKE COUNTRY CLUB",
        "MIRADA",
        "RIVER GROVE ESTATES",
        "GOODLAND HEIGHTS",
        "CHULA VISTA MANOR 1ST ADDN",
        "LEE BLVD TRADE CTR",
        "THE RESIDENCE",
        "COCONUT GROVE",
        "GRANADA LAKES",
        "RIVER OAKS",
        "MILANO",
        "SPANISH WELLS",
        "ALDEN WOODS",
        "ESPLANADE LAKE CLUB",
        "WHITE SAND VILLAS",
        "MYRTLE COVE ACRES",
        "KINGS LAKE",
        "FORT MYERS GULF ACRES",
        "PRATO AT PELICAN PRESERVE",
        "VILLAS AT KINGS LAKE",
        "PORTOFINO",
        "HOLIDAY HEIGHTS",
        "SOUTH HENDRY COUNTY",
        "PARK VIEW CONDO",
        "TAMIAMI ESTATES",
        "CUMBERLAND CONDO",
        "COURTYARDS AT GOLDEN GATE",
        "SPERLING",
        "PINEHURST ADDITION",
        "GULLWING CONDO",
        "VALENCIA COUNTRY CLUB",
        "VALENCIA LAKES",
        "PUNTA RASSA",
        "SANDPIPER BEACH CONDO",
        "780 FIFTH AVENUE SOUTH",
        "WOODGATE AT NAPLES",
        "LOVEJOY PARK",
        "PARTRIDGE PLACE",
        "BAY POINTE AT BONITA BAY",
        "POINTE AT PELICAN BAY",
        "LAKE LOUISE CONDO",
        "THE FOREST",
        "CYPRESS CONDO",
        "REGAL POINT",
        "BOWLING GREEN",
        "THE COLONNADE ON 5TH",
        "ARBOR TRACE",
        "FOUR FOUNTAINS",
        "PERIDOT AT SUNSTONE",
        "MANATEE BAY",
        "CALAIS",
        "TOSCANA AT BAY COLONY",
        "FOUNTAINHEAD",
        "ABBEY ON THE LAKE",
        "PINNACLE",
        "WATERCOURSE",
        "RIVERWALK",
        "AMBERLEY COURT",
        "COTTON GREEN",
        "CLUBSIDE RESERVE",
        "SHORE CLUB",
        "THE PALMS OF BAY BEACH",
        "BAYSHORE COMMERCIAL",
        "No Subdivision",
        "El Rio Garden Condo",
        "TWELVE OAKS",
        "LOCHMOOR",
        "HERITAGE GREENS",
        "FOUNTAINS V",
        "PARADOR",
        "LAS PALMAS",
        "WELLINGTON PLACE II",
        "MARSH LANDING",
        "BONITA VILLAGE",
        "SANTA LUCIA",
        "CARRIAGE CIRCLE OF NAPLES",
        "AQUAMARINE AT SUNSTONE",
        "BAYSHORE CONDO",
        "GULF BAY APARTMENTS",
        "VIVALDI",
        "ISLAND CLUB AT CORKSCREW WOODLANDS",
        "FOX CLUB",
        "LONGLAKE",
        "CITADEL SOUTH",
        "WILSHIRE LAKES",
        "SOMERSET AT MOORINGS",
        "PORTO ROMANO",
        "GRAND PRIX APTS",
        "SPOONBILL COVE",
        "CASTILLO AT TIBURON",
        "BOTANICAL PLACE",
        "VILLAGE",
        "ROYAL TEE COUNTRY CLUB ESTATES",
        "LAGUNA SHORES",
        "HAWTHORNE",
        "COTTAGES AT BAREFOOT",
        "HEMINGWAY PLACE",
        "OASIS OF FORT MYERS",
        "ASHTON OAKS",
        "FERNWALK",
        "GULF HARBOUR YACHT & COUNTRY CLUB",
        "VILLAGIO",
        "GULF HARBOUR",
        "WINDSONG",
        "LAKESIDE VILLAS",
        "MARBELLA LAKES",
        "BERMUDA LAGO",
        "NAPLES WALK",
        "SANDPIPER AT BONITA BAY",
        "CASCADES AT ESTERO",
        "WIND SONG CONDO",
        "HEATHERWOOD",
        "FALLING WATERS BEACH RESORT",
        "MARCO TOWERS",
        "BONITA BEACHWALK",
        "PARK SHORE LANDINGS",
        "EMERALD BEACH APARTMENTS",
        "VICTORIA PARK II",
        "FAIRWAY VILLAS",
        "COUNTRY CLUB OF NAPLES",
        "VARENNA",
        "AZURE",
        "MYSTIC RIDGE",
        "IMPERIAL SHORES",
        "EMERALD LAKES",
        "MARBELLA AT SPANISH WELLS",
        "THE GROVES",
        "SANDARAC CONDO",
        "NEVIS AT COVE TOWERS",
        "WESTSHORE AT NAPLES CAY",
        "SUMMERWIND",
        "INDIAN CREEK",
        "OAK BEND",
        "WILD PINES",
        "HIDDEN SANCTUARY VILLAGE",
        "NAPLES MIMOSA CLUB",
        "MONTEBELLO",
        "RIVER GARDEN CONDOMINIUM",
        "LAKE ARROWHEAD",
        "SUMMERLIN VILLAGE CONDO",
        "ARROYAL",
        "CHAMPIONS",
        "SPINDRIFT CLUB",
        "CAPE CORAL COMMERCIAL CENTER",
        "VENTANAS AT TIBURON",
        "MERCATO",
        "NAPLES 701",
        "BEACH CLUB COLONY CONDO",
        "ENGLEWOOD ISLES",
        "MARQUESA ROYALE",
        "SERENA",
        "MCGREGOR RESERVE",
        "CEDAR RIDGE",
        "CASA GRANDE",
        "MEADOWS OF ESTERO",
        "DELA PARK PLACE",
        "FIRANO AT NAPLES",
        "LANCASTER SQUARE",
        "MAPLEWOOD",
        "MARBELLA",
        "CLUB AT NAPLES CAY",
        "WESTGATE AT IMPERIAL GOLF ESTATES",
        "KEY HARBOUR CONDO",
        "MARINA COVE",
        "VINTAGE RESERVE",
        "THE RESIDENCES AT LA PIAZZA",
        "PALM COURT",
        "Bayview Ranchettes",
        "HIGHLAND ESTATES",
        "MARIANA HEIGHTS",
        "HERON CLUB",
        "UPPER CAPTIVA SHORES",
        "SWAN LAKE CLUB",
        "SUN DIAL OF NAPLES",
        "LAKE BARRINGTON",
        "CARENA",
        "WILLOW BROOK AT PELICAN BAY",
        "SOMMERSET VILLAS",
        "CARLTON LAKES",
        "JENNIFER SHORES",
        "VILLAS OF WHITTENBERG",
        "DEL TURA COUNTRY CLUB",
        "WATERFORD",
        "CASA DEL VIDA",
        "ASHLAND",
        "TAMARYND PLACE",
        "LITTLE HARBOUR",
        "MUTINY",
        "HUSCHKA",
        "ORANGE HARBOR MOBILE HOME PARK",
        "Fairview Isles",
        "PARK WEST",
        "FLAMINGO PARK",
        "DICKEYS JOHN R SUBD",
        "GOODLAND ISLES",
        "PORT AU PRINCE",
        "BENCHMARK CORPORATE PK LT 21",
        "SUNCOAST LAKES",
        "BLUE WATER SHORES",
        "MORSE SHORES",
        "FAIRWAY ESTATES",
        "RIVER ROYALE",
        "BIG OAKS ACRES UNIT 2",
        "SEAGRAPE",
        "BELLE VISTA ESTATES UNREC",
        "WALSH SUBDIVISION",
        "PINE VALLEY",
        "TIMBERBEND SUBD",
        "RIDGE HARBOR",
        "LAKE CLUB VILLAS",
        "PUNTA ROBALO UNRECORDED SUBDIVISION",
        "PLACID LAKES",
        "BOCILLA ISLAND CLUB CONDO",
        "BRIGHT WATER",
        "PINECREST",
        "SOUTHERN HEIGHTS",
        "LAKE SUZY",
        "Lehigh Acres",
        "FAIRVIEW ISLES",
        "JEFFCOTTS WM ADD",
        "WINDWARD CAY",
        "MANDALAY",
        "HAWTHORNE ESTATES",
        "HIGHLAND WOODS",
        "BERNWOOD PARK OF COMMERCE",
        "PINEHURST ESTATES",
        "EDGEWOOD SUBD",
        "MONTURA RANCH SEC 35",
        "RAINBOW ESTATES",
        "MONTURA RANCH SEC 36",
        "MC LAIN SUBDIVISION",
        "CAYO COSTA",
        "WHITEHEAD CREEK SUBDIVISION",
        "PALMLEE PARK",
        "WEST WIND ESTATES",
        "EL JOBEAN",
        "INDIAN PINES",
        "TWELFTH STREET PARK",
        "CHATEAU VANDERBILT",
        "COLLIERS RESERVE",
        "TIDEWATER",
        "RETREAT",
        "CORAL RIDGE ESTATES",
        "SHELL CREEK HEIGHTS",
        "CHASE SUBDIVISION UNREC",
        "TAMIAMI HEIGHTS",
        "MANATEE POINT",
        "SOUTHEAST LEHIGH",
        "GULF SHORES ESTATES",
        "TERRY TICE + VANDERWALKER",
        "SANIBEL SHORES",
        "BUCKINGHAM AIR PARK",
        "LINCOLN PARK",
        "PINE GROVE TOWNHOUSES",
        "MANATEE BAY UNRECORDED SUBDIVISION",
        "ABACO POINTE",
        "BRAEBURN",
        "COURTSIDE LANDINGS",
        "SHIPPS LANDING",
        "GARDENS OF BONITA SPRINGS",
        "SMOKEHOUSE KEY",
        "GRANDE ISLE II",
        "WILDBLUE",
        "HACIENDA VILLAGE",
        "CARRARA",
        "HEATHERMOOR",
        "BURNT STORE ISLES",
        "COQUINA AT MAPLE RIDGE",
        "SUGARMILL",
        "REFLECTION KEY",
        "THE VISTAS",
        "SUNSET HOUSE",
        "CABANA CITY",
        "SCARECROW FARMS",
        "OMEGA AT BONITA BAY",
        "CORKSCREW ESTATES",
        "ANCONA",
        "GULF COVE TRAILER PARK CO-OP",
        "VILLA SOUTH",
        "ESTATES AT WYNDEMERE",
        "BURGUNDY FARMS",
        "IMPERIAL HARBOR",
        "FLORIDIAN FARMS",
        "CRAYTON PLACE",
        "WATSON W W",
        "THE DUNES SANIBEL ISLAND",
        "EVANSTON PARK CONDO",
        "ALTAMONT PARK",
        "QUAIL CREEK",
        "NAPLES MANOR",
        "SOUTHPORT ON THE BAY",
        "LIPARI",
        "LAKEWOOD PARK",
        "CALOOSA COVE",
        "HAMMOCK CREEK",
        "ANGLERS COVE",
        "GULF ISLAND MANOR",
        "PINE LAKES COUNTRY CLUB",
        "PINE VIEW VILLAS",
        "GLADES HAVEN RESORT AND MARINA",
        "TEE AND GREEN ESTATES",
        "DEER RUN FARMS",
        "TRADEWINDS APTS OF MARCO ISLAND",
        "MORNINGSIDE",
        "ROCK HARBOR",
        "Fort Myers Villas",
        "MERIDA",
        "RENAISSANCE VILLAGE",
        "SUNWARD CONDO",
        "CREEKSIDE CROSSING",
        "WILLIAMSBURG",
        "CRYSTAL LAKES",
        "MATLACHA ISLES",
        "SOUTHWINDS APTS OF MARCO ISLAND",
        "CAPE ROYAL",
        "REGENT",
        "MARCO VILLA",
        "PLAN OF RIVERSIDE",
        "SARACENO",
        "CASSIA",
        "VISTA POINTE",
        "RUBICON CONDO",
        "VIKING CONDO",
        "LAKE PLACID WATERWAY",
        "SUN-N-FUN MOBILE HOME VILLAGE",
        "BAYPORT VILLAGE",
        "CARLETON ESTATES",
        "SUNSET LAKE CONDO",
        "STRATFORD PLACE CONDO",
        "SEABURY",
        "FOUR MILE COVE",
        "TUSCANY",
        "VINTAGE BAY",
        "THE VILLAS AT VENEZIA",
        "TWIN LAKES",
        "Fort Denaud",
        "HANSONS W STANLEY SUBD",
        "LAUREL ESTATES",
        "MERION VILLAGE",
        "TRAILSIDE",
        "BROADVIEW VILLAS",
        "TUSCANY COVE",
        "KELLY PLAZA",
        "WOODLAKE AT BONITA BAY",
        "PRINCESS DEL MAR",
        "MORNINGSTAR",
        "MONTEROSSO",
        "COUNTRY CLUB",
        "DROP ANCHOR MOBILE HOME",
        "PALOMA",
        "Gullwing Beach Resort",
        "VENEZIA",
        "RIVER TERRACE CONDO",
        "SOMERSET",
        "WESTMINSTER",
        "BURNT STORE COLONY",
        "CHARLESTON PARK",
        "LABELLE TERRACE",
        "ROSEMARY PARK",
        "PRESERVE III",
        "BRIGHTON AT BAY COLONY",
        "MARINER POINTE CONDO",
        "ISLAND MANOR APTS",
        "ROYAL SEAFARER",
        "WINDWARD ISLE",
        "EVANS ADDITION",
        "ISLES OF PORTO VISTA",
        "EUROPEAN TOWNHOUSE",
        "COSTA DEL SOL",
        "COLONIES",
        "VERCELLI",
        "BOCA CIEGA MANOR",
        "TUSCANY ISLE",
        "BAREFOOT BAY",
        "TERRACE III AT RIVERWALK",
        "RIVIERA CLUB",
        "HEITMANS",
        "BELIZE",
        "PERIWINKLE PINES",
        "CAPTAINS BAY SOUTH",
        "ESTERO BAY SHORES",
        "VENETIAN POINTE",
        "PROMENADE EAST",
        "SAPPHIRE COVE",
        "MANATEE COVE",
        "PEPPER TREE",
        "SURF SONG CONDO",
        "FUNCKS SUBD",
        "SOUTH POINTE SOUTH",
        "GULLWING BEACH RESORT",
        "POINCIANA VILLAGE",
        "REMINGTON OAKS",
        "MONTURA RANCH SEC 34",
        "LA PENINSULA",
        "FLAGHOLE",
        "TRADEWINDS",
        "GULF EAST",
        "ESPERANZA",
        "BLACK BEAR RIDGE",
        "VICTORIA COVE CONDO",
        "DAVIS WOODS CONDOMINIUM",
        "TRAWLER VILLAGE",
        "IMMOKALEE HIGHLANDS",
        "FOXMOOR",
        "DUCHESS I CONDO",
        "PINE ISLAND VILLAS",
        "ESTERO PARK",
        "HAMPTON LAKES",
        "LAZY DAYS MOBILE VILLAGE",
        "RIVERS CONDO",
        "MILL RUN",
        "SUNSET",
        "BRENTWOOD",
        "TALL PINES",
        "GRIFFIN ESTATES",
        "GLENWOOD PARK",
        "MARIPOSA",
        "CYPRESS LANDING",
        "ST. TROPEZ",
        "RIVERWOODS PLANTATION",
        "NORTHWOOD",
        "GULF HARBOR",
        "PIRATES COVE",
        "EMERALD WOODS",
        "CATALINA ISLES",
        "STONEBRIDGE",
        "COCONUT RIVER",
        "CALUSA RIDGE",
        "HILLS T.P.",
        "EVERHIGHT ACRES",
        "LE DAUPHIN",
        "LUCARNO",
        "BROOKSHIRE VILLAGE",
        "SHALLOWS",
        "AQUA SHORES",
        "PELICAN LAKE RV RESORT",
        "MARCELLO",
        "BLIND PASS CONDO",
        "GULF SHORES",
        "LEAWOOD LAKES",
        "HOLIDAY MANOR",
        "HOLIDAY PARK",
        "BERMUDA BAY",
        "BLUE HERON",
        "MCGREGOR VISTA",
        "BIMINI ISLE",
        "BRITANNIA II",
        "SAWGRASS POINT",
        "TRIANA",
        "HARBOURSIDE",
        "VERANDA",
        "ROYAL GREENS",
        "SAVANNAH LAKES",
        "HICKORY SHORES",
        "AMADOR",
        "ONE",
        "FOREST LAKE TOWNHOMES",
        "SOUTH BAY PLANTATION",
        "HARLEM",
        "RAFFIA PRESERVE",
        "CYPRESS WALK",
        "SUNDIAL OF SANIBEL",
        "FRANKS",
        "LES CHATEAUX",
        "BAY HAVEN",
        "PINE ISLAND COVE",
        "ORCHID HARBOUR VILLAS CONDO",
        "LAUSANNE",
        "TERRA PALMA",
        "CAMDEN SQUARE",
        "BAY CEDAR",
        "KEEL CLUB",
        "STERLING LAKES II",
        "COLONNADE AT FORUM",
        "EVEREST CONDO",
        "TERRACE IV",
        "MANOR",
        "ROYAL POINTE",
        "CAPE GARDENS CONDO",
        "LAKE ARROWHEAD MOB VILLAGE",
        "CYPRESS PRESERVE",
        "ABBEY AT BERKSHIRE VILLAGE",
        "MARINA MANOR",
        "JASMINE BAY SOUTH"
    ].sort()
}